import { defineConfig } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { fileURLToPath } from 'node:url';

const p = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));

/** The deployable app: ONE static html file (RUN loads a static build; no server). base './' so it works from a sub-path. */
export default defineConfig(({ mode }) => ({
  base: './',
  plugins: [viteSingleFile()],
  resolve: {
    alias: {
      // browser build: the script host uses the transpile-only compiler (no TypeScript program, no Node fs)
      // the RUN SDK only exists in a RUN build (`npm run build:run`); everywhere else it is a harmless stub
      ...(mode === 'run' ? {} : { '@series-inc/rundot-game-sdk/api': p('./src/platform/sdk-stub.ts') }),
      './compile.js': p('../../packages/script/src/compile-lite.ts'),
      './quickjs-loader.js': p('../../packages/script/src/quickjs-loader-browser.ts'),
      './qjs.js': p('../../packages/script/src/qjs-browser.ts'),
      '@hm/contracts': p('../../packages/contracts/src/index.ts'),
      '@hm/kernel': p('../../packages/kernel/src/index.ts'),
      '@hm/script': p('../../packages/script/src/index.ts'),
      '@hm/sim': p('../../packages/sim/src/index.ts'),
      '@hm/platform': p('../../packages/platform/src/index.ts'),
      '@hm/physics': p('../../packages/physics/src/index.ts'),
      '@hm/render': p('../../packages/render/src/index.ts'),
      '@hm/ui': p('../../packages/ui/src/index.ts'),
      '@hm/engine': p('../../packages/engine/src/index.ts'),
      '@hm/terrain': p('../../packages/terrain/src/index.ts'),
      '@hm/game': p('../../packages/game/src/index.ts'),
      '@hm/racing': p('../../packages/racing/src/index.ts'),
      '@hm/racers': p('../../packages/racers/src/index.ts'),
      '@hm/trackgen': p('../../packages/trackgen/src/index.ts'),
      '@hm/content': p('../../packages/content/src/index.ts'),
      '@hm/looks': p('../../packages/looks/src/index.ts'),
      '@hm/raceflow': p('../../packages/raceflow/src/index.ts'),
      '@hm/input': p('../../packages/input/src/index.ts'),
      '@hm/goblins': p('../../packages/goblins/src/index.ts'),
      '@hm/audio': p('../../packages/audio/src/index.ts'),
      '@hm/trackedit': p('../../packages/trackedit/src/index.ts'),
      '@hm/terrainops': p('../../packages/terrainops/src/index.ts'),
      '@hm/scatter': p('../../packages/scatter/src/index.ts'),
      '@hm/modulation': p('../../packages/modulation/src/index.ts'),
      '@hm/modui': p('../../packages/modui/src/index.ts'),
      '@hm/soundlab': p('../../packages/soundlab/src/index.ts'),
      '@hm/screens': p('../../packages/screens/src/index.ts'),
      '@hm/itemdefs': p('../../packages/itemdefs/src/index.ts'),
      '@hm/hudlayout': p('../../packages/hudlayout/src/index.ts'),
      '@hm/soundpack': p('../../packages/soundpack/src/index.ts'),
      '@hm/texgraph': p('../../packages/texgraph/src/index.ts'),
      '@hm/tracklayouts': p('../../packages/tracklayouts/src/index.ts'),
      '@hm/evolve': p('../../packages/evolve/src/index.ts'),
      '@hm/lineage': p('../../packages/lineage/src/index.ts'),
      '@hm/voxelart': p('../../packages/voxelart/src/index.ts'),
      '@hm/camerarig': p('../../packages/camerarig/src/index.ts'),
      '@hm/plugs': p('../../packages/plugs/src/index.ts'),
      '@hm/islands': p('../../packages/islands/src/index.ts'),
      '@hm/lighting': p('../../packages/lighting/src/index.ts'),
      '@hm/buildkit': p('../../packages/buildkit/src/index.ts'),
      '@hm/gizmo': p('../../packages/gizmo/src/index.ts'),
      '@hm/triggers': p('../../packages/triggers/src/index.ts'),
      '@hm/primitives': p('../../packages/primitives/src/index.ts'),
      '@hm/physmat': p('../../packages/physmat/src/index.ts'),
      '@hm/wiregraph': p('../../packages/wiregraph/src/index.ts'),
      '@hm/splineroad': p('../../packages/splineroad/src/index.ts'),
      '@hm/camtrack': p('../../packages/camtrack/src/index.ts'),
      '@hm/walkpath': p('../../packages/walkpath/src/index.ts'),
      '@hm/lightplace': p('../../packages/lightplace/src/index.ts'),
      '@hm/voxelcsg': p('../../packages/voxelcsg/src/index.ts'),
      '@hm/soundscape': p('../../packages/soundscape/src/index.ts'),
      '@hm/npcbrain': p('../../packages/npcbrain/src/index.ts'),
      '@hm/particles': p('../../packages/particles/src/index.ts'),
      '@hm/selectset': p('../../packages/selectset/src/index.ts'),
      '@hm/voxelnature': p('../../packages/voxelnature/src/index.ts'),
      '@hm/worldrules': p('../../packages/worldrules/src/index.ts'),
      '@hm/anim': p('../../packages/anim/src/index.ts'),
      '@hm/avatarlook': p('../../packages/avatarlook/src/index.ts'),
      '@hm/assembler': p('../../packages/assembler/src/index.ts'),
      '@hm/pbrgrass': p('../../packages/pbrgrass/src/index.ts'),
      '@hm/voxpartshead': p('../../packages/voxpartshead/src/index.ts'),
      '@hm/toolcatalog': p('../../packages/toolcatalog/src/index.ts'),
      '@hm/smoothvox': p('../../packages/smoothvox/src/index.ts'),
      '@hm/voxpartsbody': p('../../packages/voxpartsbody/src/index.ts'),
      '@hm/uistack': p('../../packages/uistack/src/index.ts'),
      '@hm/tutorial': p('../../packages/tutorial/src/index.ts'),
      '@hm/juice': p('../../packages/juice/src/index.ts'),
      '@hm/activities': p('../../packages/activities/src/index.ts'),
      '@hm/voxelsculpt': p('../../packages/voxelsculpt/src/index.ts'),
      '@hm/motion': p('../../packages/motion/src/index.ts'),
      '@hm/voxel': p('../../packages/voxel/src/index.ts'),
      '@hm/tools': p('../../packages/tools/src/index.ts'),
    },
  },
  build: { target: 'es2022', outDir: 'dist', emptyOutDir: true },
}));
