import { defineConfig } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { fileURLToPath } from 'node:url';

const p = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));

/** The deployable app: ONE static html file (RUN loads a static build; no server). base './' so it works from a sub-path. */
export default defineConfig(({ mode }) => ({
  base: './',
  plugins: [viteSingleFile()],
  // which game this build is (src/edition.ts): `HM_EDITION=goblin-racing npm run build` for the Goblin Racing launch; SetMix by default
  define: { __HM_EDITION__: JSON.stringify(process.env.HM_EDITION ?? 'setmix') },
  resolve: {
    alias: {
      // browser build: the script host uses the transpile-only compiler (no TypeScript program, no Node fs)
      // the RUN SDK only exists in a RUN build (`npm run build:run`); everywhere else it is a harmless stub
      ...(mode === 'run' ? {} : { '@series-inc/rundot-game-sdk/api': p('./src/platform/sdk-stub.ts') }),
      './compile.js': p('../../packages/script/src/compile-lite.ts'),
      './quickjs-loader.js': p('../../packages/script/src/quickjs-loader-browser.ts'),
      './qjs.js': p('../../packages/script/src/qjs-browser.ts'),
      '@hm/contracts': p('../../packages/contracts/src/index.ts'),
      '@hm/kernel': p('../../packages/kernel/src/index.ts'),
      '@hm/script': p('../../packages/script/src/index.ts'),
      '@hm/sim': p('../../packages/sim/src/index.ts'),
      '@hm/platform': p('../../packages/platform/src/index.ts'),
      '@hm/physics': p('../../packages/physics/src/index.ts'),
      '@hm/render': p('../../packages/render/src/index.ts'),
      '@hm/ui': p('../../packages/ui/src/index.ts'),
      '@hm/engine': p('../../packages/engine/src/index.ts'),
      '@hm/terrain': p('../../packages/terrain/src/index.ts'),
      '@hm/game': p('../../packages/game/src/index.ts'),
      '@hm/racing': p('../../packages/racing/src/index.ts'),
      '@hm/racers': p('../../packages/racers/src/index.ts'),
      '@hm/trackgen': p('../../packages/trackgen/src/index.ts'),
      '@hm/content': p('../../packages/content/src/index.ts'),
      '@hm/looks': p('../../packages/looks/src/index.ts'),
      '@hm/raceflow': p('../../packages/raceflow/src/index.ts'),
      '@hm/input': p('../../packages/input/src/index.ts'),
      '@hm/goblins': p('../../packages/goblins/src/index.ts'),
      '@hm/audio': p('../../packages/audio/src/index.ts'),
      '@hm/trackedit': p('../../packages/trackedit/src/index.ts'),
      '@hm/terrainops': p('../../packages/terrainops/src/index.ts'),
      '@hm/scatter': p('../../packages/scatter/src/index.ts'),
      '@hm/modulation': p('../../packages/modulation/src/index.ts'),
      '@hm/modui': p('../../packages/modui/src/index.ts'),
      '@hm/soundlab': p('../../packages/soundlab/src/index.ts'),
      '@hm/screens': p('../../packages/screens/src/index.ts'),
      '@hm/itemdefs': p('../../packages/itemdefs/src/index.ts'),
      '@hm/hudlayout': p('../../packages/hudlayout/src/index.ts'),
      '@hm/soundpack': p('../../packages/soundpack/src/index.ts'),
      '@hm/texgraph': p('../../packages/texgraph/src/index.ts'),
      '@hm/tracklayouts': p('../../packages/tracklayouts/src/index.ts'),
      '@hm/evolve': p('../../packages/evolve/src/index.ts'),
      '@hm/lineage': p('../../packages/lineage/src/index.ts'),
      '@hm/voxelart': p('../../packages/voxelart/src/index.ts'),
      '@hm/camerarig': p('../../packages/camerarig/src/index.ts'),
      '@hm/plugs': p('../../packages/plugs/src/index.ts'),
      '@hm/islands': p('../../packages/islands/src/index.ts'),
      '@hm/lighting': p('../../packages/lighting/src/index.ts'),
      '@hm/buildkit': p('../../packages/buildkit/src/index.ts'),
      '@hm/gizmo': p('../../packages/gizmo/src/index.ts'),
      '@hm/triggers': p('../../packages/triggers/src/index.ts'),
      '@hm/primitives': p('../../packages/primitives/src/index.ts'),
      '@hm/physmat': p('../../packages/physmat/src/index.ts'),
      '@hm/keyframes': p('../../packages/keyframes/src/index.ts'),
      '@hm/erosion': p('../../packages/erosion/src/index.ts'),
      '@hm/wiregraph': p('../../packages/wiregraph/src/index.ts'),
      '@hm/splineroad': p('../../packages/splineroad/src/index.ts'),
      '@hm/camtrack': p('../../packages/camtrack/src/index.ts'),
      '@hm/walkpath': p('../../packages/walkpath/src/index.ts'),
      '@hm/smoothvox2': p('../../packages/smoothvox2/src/index.ts'),
      '@hm/toolanims': p('../../packages/toolanims/src/index.ts'),
      '@hm/tooljuice': p('../../packages/tooljuice/src/index.ts'),
      '@hm/vox': p('../../packages/vox/src/index.ts'),
      '@hm/schematic': p('../../packages/schematic/src/index.ts'),
      '@hm/puppet': p('../../packages/puppet/src/index.ts'),
      '@hm/decals': p('../../packages/decals/src/index.ts'),
      '@hm/kart': p('../../packages/kart/src/index.ts'),
      '@hm/kinematic': p('../../packages/kinematic/src/index.ts'),
      '@hm/musicbox': p('../../packages/musicbox/src/index.ts'),
      '@hm/chunkworld': p('../../packages/chunkworld/src/index.ts'),
      '@hm/pixels': p('../../packages/pixels/src/index.ts'),
      '@hm/questline': p('../../packages/questline/src/index.ts'),
      '@hm/machines': p('../../packages/machines/src/index.ts'),
      '@hm/market': p('../../packages/market/src/index.ts'),
      '@hm/rocket': p('../../packages/rocket/src/index.ts'),
      '@hm/ragdoll': p('../../packages/ragdoll/src/index.ts'),
      '@hm/navgrid': p('../../packages/navgrid/src/index.ts'),
      '@hm/hull': p('../../packages/hull/src/index.ts'),
      '@hm/remesh': p('../../packages/remesh/src/index.ts'),
      '@hm/lightplace': p('../../packages/lightplace/src/index.ts'),
      '@hm/voxelcsg': p('../../packages/voxelcsg/src/index.ts'),
      '@hm/soundscape': p('../../packages/soundscape/src/index.ts'),
      '@hm/npcbrain': p('../../packages/npcbrain/src/index.ts'),
      '@hm/particles': p('../../packages/particles/src/index.ts'),
      '@hm/selectset': p('../../packages/selectset/src/index.ts'),
      '@hm/voxelnature': p('../../packages/voxelnature/src/index.ts'),
      '@hm/worldrules': p('../../packages/worldrules/src/index.ts'),
      '@hm/anim': p('../../packages/anim/src/index.ts'),
      '@hm/avatarlook': p('../../packages/avatarlook/src/index.ts'),
      '@hm/assembler': p('../../packages/assembler/src/index.ts'),
      '@hm/pbrgrass': p('../../packages/pbrgrass/src/index.ts'),
      '@hm/voxpartshead': p('../../packages/voxpartshead/src/index.ts'),
      '@hm/toolcatalog': p('../../packages/toolcatalog/src/index.ts'),
      '@hm/smoothvox': p('../../packages/smoothvox/src/index.ts'),
      '@hm/voxpartsbody': p('../../packages/voxpartsbody/src/index.ts'),
      '@hm/uistack': p('../../packages/uistack/src/index.ts'),
      '@hm/tutorial': p('../../packages/tutorial/src/index.ts'),
      '@hm/juice': p('../../packages/juice/src/index.ts'),
      '@hm/activities': p('../../packages/activities/src/index.ts'),
      '@hm/voxelsculpt': p('../../packages/voxelsculpt/src/index.ts'),
      '@hm/motion': p('../../packages/motion/src/index.ts'),
      '@hm/voxel': p('../../packages/voxel/src/index.ts'),
      '@hm/tools': p('../../packages/tools/src/index.ts'),
      '@hm/fauna': p('../../packages/fauna/src/index.ts'),
      '@hm/flora': p('../../packages/flora/src/index.ts'),
      '@hm/vault': p('../../packages/vault/src/index.ts'),
      '@hm/fidelity': p('../../packages/fidelity/src/index.ts'),
      '@hm/plotterrain': p('../../packages/plotterrain/src/index.ts'),
      '@hm/groundshader': p('../../packages/groundshader/src/index.ts'),
      '@hm/plume': p('../../packages/plume/src/index.ts'),
      '@hm/labkit': p('../../packages/labkit/src/index.ts'),
      '@hm/plotsim': p('../../packages/plotsim/src/index.ts'),
      '@hm/structure': p('../../packages/structure/src/index.ts'),
      '@hm/lattice': p('../../packages/lattice/src/index.ts'),
      '@hm/substrate': p('../../packages/substrate/src/index.ts'),
      '@hm/fieldkit': p('../../packages/fieldkit/src/index.ts'),
      '@hm/cartlab': p('../../packages/cartlab/src/index.ts'),
      '@hm/plotcodec': p('../../packages/plotcodec/src/index.ts'),
      '@hm/consolemill': p('../../packages/consolemill/src/index.ts'),
      '@hm/shareware': p('../../packages/shareware/src/index.ts'),
    },
  },
  assetsInclude: ['**/*.fbx', '**/*.bin'],
  build: { target: 'es2022', outDir: 'dist', emptyOutDir: true, assetsInlineLimit: 100_000_000 },
}));
