/**
 * Build step: raw magenta-background renders → keyed, trimmed, 512-max transparent PNG masters + manifest.
 *   npx tsx scripts/key-avatar-parts.ts
 * Reads   public/avatar-parts/raw/*.{png,jpg}   (sniffs magic bytes — generators often return JPEG named .png)
 * Writes  public/avatar-parts/keyed/<id>.png
 *         src/hmgp2/painted-parts.generated.ts   (dimensions + QA, consumed by the compositor)
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import jpeg from 'jpeg-js';
import { PNG } from 'pngjs';
import { DEFAULT_KEY_PARAMS, keyPart, type Rgba } from '../src/hmgp2/chroma-key';

const RAW = 'public/avatar-parts/raw';
const OUT = 'public/avatar-parts/keyed';
mkdirSync(OUT, { recursive: true });

function decode(buf: Buffer): { img: Rgba; format: 'jpeg' | 'png' } {
  if (buf[0] === 0xff && buf[1] === 0xd8) {
    const d = jpeg.decode(buf, { useTArray: true, formatAsRGBA: true, maxMemoryUsageInMB: 1024 });
    return { img: { width: d.width, height: d.height, data: new Uint8ClampedArray(d.data.buffer) }, format: 'jpeg' };
  }
  if (buf[0] === 0x89 && buf[1] === 0x50) {
    const p = PNG.sync.read(buf);
    return { img: { width: p.width, height: p.height, data: new Uint8ClampedArray(p.data.buffer, p.data.byteOffset, p.data.length) }, format: 'png' };
  }
  throw new Error('unknown image format');
}

const entries: string[] = [];
for (const file of readdirSync(RAW).sort()) {
  if (!/\.(png|jpe?g)$/i.test(file)) continue;
  const id = file.replace(/\.(png|jpe?g)$/i, '');
  const { img, format } = decode(readFileSync(path.join(RAW, file)));
  const t0 = Date.now();
  const { master, qa } = keyPart(img, DEFAULT_KEY_PARAMS, 512);
  const png = new PNG({ width: master.width, height: master.height });
  png.data = Buffer.from(master.data.buffer, master.data.byteOffset, master.data.length);
  const bytes = PNG.sync.write(png, { colorType: 6 });
  writeFileSync(path.join(OUT, `${id}.png`), bytes);
  console.log(`${id.padEnd(30)} ${format} ${img.width}×${img.height} → ${master.width}×${master.height}  ${(bytes.length / 1024).toFixed(0)} KB  key=${qa.key}  ${qa.verdict}  ${Date.now() - t0} ms ${qa.notes.join('; ')}`);
  entries.push(`  '${id}': { file: '/avatar-parts/keyed/${id}.png', raw: '/avatar-parts/raw/${file}', sourceFormat: '${format}', width: ${master.width}, height: ${master.height}, qa: ${JSON.stringify({ verdict: qa.verdict, key: qa.key, keyDeviation: qa.keyDeviation, coverage: qa.coverage, residualMagenta: qa.residualMagenta, borderTouch: qa.borderTouch, notes: qa.notes })} },`);
}

writeFileSync('src/hmgp2/painted-parts.generated.ts', `// AUTO-GENERATED by scripts/key-avatar-parts.ts — do not edit by hand.
export interface KeyedPartFile {
  file: string; raw: string; sourceFormat: 'jpeg' | 'png'; width: number; height: number;
  qa: { verdict: 'pass' | 'warn' | 'fail'; key: number[]; keyDeviation: number; coverage: number; residualMagenta: number; borderTouch: number; notes: string[] };
}
export const KEYED_PARTS: Record<string, KeyedPartFile> = {
${entries.join('\n')}
};
`);
