#!/bin/bash
# Assemble 13-sheet-human-scientist.png (2560x1440): the human scientist, the player.
# Panels live in panels/13 (tracked, like panels/12). The scale annotations are drawn
# to true proportions from the canon numbers (scientist 1.75 m, gate opening
# 2.6 x 1.7 m, goblin 1.3 m) — never generated by a model.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; source "$ROOT/tools/lib.sh"
T="$ROOT/scratch/13"; mkdir -p "$T"; S="$ROOT/panels/13"
BRD="#333941"
FLOOR=800                      # the shared floor line of row 1, px in the sheet

# ---- helpers -----------------------------------------------------------------
panelbg() { convert "$1" -crop 80x18+0+0 +repage -resize 1x1 -format "%[pixel:p{0,0}]" info:; }
fitpad() { local bg; bg=$(panelbg "$1")
  convert -size "$2" xc:"$bg" \( "$1" -resize "$2" \) -gravity center -composite \
    -bordercolor "$BRD" -border 1 "$3"; }
coverfit() { convert "$1" -resize "$2^" -gravity center -extent "$2" -bordercolor "$BRD" -border 1 "$3"; }
caption() { local cv=$1 x=$2 y=$3 m=$4 s=$5
  convert "$cv" -font $BOLD -pointsize 20 -fill "$ACC" -gravity northwest -annotate "+$x+$y" "$m" \
    -font $FONT -pointsize 16 -fill "$SUB" -gravity northwest -annotate "+$x+$((y+27))" "$s" "$cv"; }

# ---- row 1: turnaround + variants, one shared floor line, same 1.75 m ---------
S_T=55; S_V=55
convert "$S/13-turnaround.png" -crop 1320x670+30+50 +repage -resize $((1320*S_T/100))x -bordercolor "$BRD" -border 1 "$T/turn.png"
TURN_X=230; TURN_Y=$(( FLOOR - 663*S_T/100 ))
FRONT_CX=$(( TURN_X + 163*S_T/100 ))
convert "$S/13-variants.png" -crop 1350x685+35+58 +repage -resize $((1350*S_V/100))x -bordercolor "$BRD" -border 1 "$T/var.png"
VAR_X=1000; VAR_Y=$(( FLOOR - 666*S_V/100 ))

# ---- row 2 panels: crop each source to its figure, then fit the cell ---------
P_Y=830; P_H=380
crop1() { convert "$S/13-$1.png" -crop "$2" +repage "$T/x-$1.png"; }
crop1 exploded 689x730+360+12
crop1 pose-idle 308x730+551+10
crop1 pose-wave 359x720+506+24
crop1 pose-walk 388x720+512+17
crop1 stage1 973x690+210+34
R2=( "40:440:x-exploded:EXPLODED VIEW — RIGID PARTS:one body in nine parts, flat cut faces at every joint" \
     "500:270:x-pose-idle:BREATHING IDLE:a still, natural idle loop" \
     "780:270:x-pose-wave:WAVE:a greeting to visitors in your lab" \
     "1060:270:x-pose-walk:MID-STRIDE WALK:the walk cycle, coat hem swinging" \
     "1350:480:x-stage1:STAGE 1 ON THE PLANET:walking through makes you low poly" \
     "1850:700:context-lab:IN CONTEXT — BESIDE THE GATE:the 01 lab, gate off — the room and the scale she stands in" )
for spec in "${R2[@]}"; do
  IFS=':' read -r px pw key cap sub <<< "$spec"
  if [ "$key" = "context-lab" ]; then coverfit "$S/13-$key.png" "${pw}x${P_H}" "$T/r2-$key.png"
  else fitpad "$T/$key.png" "${pw}x${P_H}" "$T/r2-$key.png"; fi
done

# ---- canvas ------------------------------------------------------------------
convert -size 2560x1440 xc:"$BG" \
  -font $BOLD -pointsize 44 -fill "$FG" -gravity northwest -annotate +40+22 \
    "SETMIX — THE HUMAN SCIENTIST, THE PLAYER" \
  -font $FONT -pointsize 25 -fill "$SUB" -gravity northwest -annotate +40+86 \
    "1.75 m in a 2.6 m gate opening · one parametric character in smooth rigid parts · seen in the avatar maker, in menus beside the gate, and by visiting players" \
  \( "$T/turn.png" \) -gravity northwest -geometry +${TURN_X}+${TURN_Y} -composite \
  \( "$T/var.png" \)  -gravity northwest -geometry +${VAR_X}+${VAR_Y} -composite \
  "$T/base.png"

# ---- true-scale annotations on the turnaround --------------------------------
FIG_H=$(( 644*S_T/100 ))                # the figure, px on the sheet
M_PX=$(( FIG_H*100/175 ))               # one metre, the same on the variants
OPEN_H=$(( M_PX*26/10 )); OPEN_W=$(( M_PX*17/10 ))
OX1=$(( FRONT_CX - OPEN_W/2 )); OX2=$(( FRONT_CX + OPEN_W/2 )); OY1=$(( FLOOR - OPEN_H ))
HX=$(( OX1 - 24 ))
convert -background none -fill "$ACC" -font $BOLD -pointsize 19 \
  label:"1.75 m  —  THE SCIENTIST" -rotate -90 "$T/vlab.png"
VL_H=$(identify -format "%h" "$T/vlab.png")
# dashed outline of the 2.6 m gate opening behind her, and her 1.75 m dimension
convert "$T/base.png" -stroke "$ACC" -strokewidth 2 -fill none \
  -draw "stroke-dasharray 14 10 rectangle $OX1,$OY1 $OX2,$FLOOR" \
  -draw "line $HX,$FLOOR $HX,$((FLOOR-FIG_H))" \
  -draw "line $((HX-8)),$FLOOR $((HX+8)),$FLOOR" \
  -draw "line $((HX-8)),$((FLOOR-FIG_H)) $((HX+8)),$((FLOOR-FIG_H))" \
  -stroke "#8a7a52" -strokewidth 1 -fill none \
  -draw "stroke-dasharray 6 8 line $HX,$FLOOR $((TURN_X-4)),$FLOOR" \
  -draw "stroke-dasharray 6 8 line $HX,$((FLOOR-FIG_H)) $((TURN_X-4)),$((FLOOR-FIG_H))" \
  -stroke none -fill "$ACC" -font $BOLD -pointsize 20 -gravity northwest \
  -annotate +$OX1+$((OY1-28)) "THE GATE OPENING — 2.6 m" \
  "$T/base.png"
convert "$T/base.png" \( "$T/vlab.png" \) -gravity northwest -geometry +92+$(( FLOOR - FIG_H/2 - VL_H/2 )) -composite "$T/base.png"
convert -background "#000000aa" -fill "$FG" -font $FONT -pointsize 17 -size 190x \
  caption:"2.6 m tall\n1.7 m wide\ntwo goblins stacked" "$T/sz.png"
convert "$T/base.png" \( "$T/sz.png" \) -gravity northwest -geometry +$((OX2+14))+$((OY1+6)) -composite "$T/base.png"

# ---- scale box (right of row 1) ----------------------------------------------
SB_X=1755; SB_W=795; SB_Y=112; SB_H=688
convert -size ${SB_W}x${SB_H} xc:"$PNL" "$T/sb.png"
U=70; BASE=316      # 70 px per metre, one baseline
for spec in "60:182:#5f666f:2.6 m:gate opening:2.6 x 1.7 m" \
            "190:123:$ACC:1.75 m:the scientist:1.5 goblins" \
            "320:91:#7cff4d:1.3 m:goblin:half the opening"; do
  IFS=':' read -r bx bh bc bl b1 b2 <<< "$spec"
  convert "$T/sb.png" -fill "$bc" -stroke none -draw "rectangle $bx,$((BASE-bh)) $(($bx+46)),$BASE" \
    -font $BOLD -pointsize 19 -fill "$FG" -gravity northwest -annotate +$((bx+2))+$((BASE-bh-28)) "$bl" \
    -font $FONT -pointsize 17 -fill "$ACC" -gravity northwest -annotate +$((bx+2))+$((BASE+14)) "$b1" \
    -font $FONT -pointsize 16 -fill "$SUB" -gravity northwest -annotate +$((bx+2))+$((BASE+38)) "$b2" "$T/sb.png"
done
convert "$T/sb.png" -font $BOLD -pointsize 26 -fill "$ACC" -gravity northwest -annotate +26+16 "SCALE" \
  -font $FONT -pointsize 19 -fill "$FG" -gravity northwest \
  -annotate +424+150 "the opening reads as two" \
  -annotate +424+176 "goblins stacked, never" \
  -annotate +424+202 "three — the goblin is" \
  -annotate +424+228 "exactly half its height" \
  -stroke "#3a3f47" -strokewidth 1 -fill none -draw "line 26,388 769,388" \
  -stroke none -font $BOLD -pointsize 24 -fill "$ACC" -gravity northwest -annotate +26+400 "THE NINE RIGID PARTS" \
  -font $FONT -pointsize 19 -fill "$FG" -gravity northwest \
  -annotate +26+438 "1   head + hair + goggles            2   torso + collar + coat" \
  -annotate +26+464 "3   upper arm  x2                        4   forearm + sleeve cuff  x2" \
  -annotate +26+490 "5   gloved hand  x2                    6   belt + pelvis" \
  -annotate +26+516 "7   thigh  x2                                 8   shin + knee pad  x2" \
  -annotate +26+542 "9   boot  x2" \
  -stroke "#3a3f47" -strokewidth 1 -fill none -draw "line 26,568 769,568" \
  -stroke none -font $BOLD -pointsize 24 -fill "$ACC" -gravity northwest -annotate +26+580 "WHERE THE JOINTS HIDE" \
  -font $FONT -pointsize 17 -fill "$FG" -gravity northwest \
  -annotate +26+616 "neck: collar · shoulders: sleeve seam · elbows: pad + seam" \
  -annotate +26+642 "wrists: cuff / glove edge · waist: belt · hips: coat hem" \
  -annotate +26+668 "knees: knee pad · ankles: boot top — every joint a flat cut face" \
  "$T/sb.png"
convert "$T/base.png" \( "$T/sb.png" \) -gravity northwest -geometry +${SB_X}+${SB_Y} -composite "$T/base.png"

# ---- row 2 paste + captions --------------------------------------------------
for spec in "${R2[@]}"; do
  IFS=':' read -r px pw key cap sub <<< "$spec"
  convert "$T/base.png" \( "$T/r2-$key.png" \) -gravity northwest -geometry +${px}+${P_Y} -composite "$T/base.png"
  caption "$T/base.png" "$px" 1224 "$cap" "$sub"
done

# ---- footer ------------------------------------------------------------------
fcol() { local x=$1 y=$2 h=$3 a=$4 b=$5 c=$6 d=$7
  convert "$T/base.png" -font $BOLD -pointsize 22 -fill "$ACC" -gravity northwest -annotate +$x+$y "$h" \
    -font $FONT -pointsize 19 -fill "$FG" -gravity northwest \
    -annotate +$x+$((y+30)) "$a" -annotate +$x+$((y+56)) "$b" \
    -annotate +$x+$((y+82)) "$c" -annotate +$x+$((y+108)) "$d" "$T/base.png"; }
fcol 40 1300 "GARMENT PIECES" \
  "fitted work jumpsuit — zip front, collar, reinforced knees, cuffs" \
  "short lab coat — collar, two deep pockets, hem at mid-thigh" \
  "utility belt + pouches + cartridge holster (the presets are cartridges)" \
  "gloves · laced boots · goggles (forehead or worn) · ID badge clip, blank card"
fcol 940 1300 "VARIANTS — ONE PARAMETRIC CHARACTER" \
  "skin tones x6 · builds light / medium / heavy · ages late 20s to 50s" \
  "hair: short crop, buzz, bun, ponytail, curls, shaved sides · facial hair on some" \
  "colourways: white coat / teal · slate / orange · navy / yellow" \
  "bone / graphite · white / rust · light grey / deep green · goggles up or worn"
fcol 1810 1300 "WHERE SHE IS SEEN · READ WITH" \
  "avatar maker in the lab — on a turntable, before the gate first turns on" \
  "menus, beside the gate · other players visiting your lab · in play, through her eyes" \
  "sheet 06 — the gate she stands in · sheet 12 — the machines she feeds" \
  "sheets 09 / 10 — the world she makes · she is the player: adult, capable, practical"

convert "$T/base.png" -strip -define png:compression-level=9 "$ROOT/13-sheet-human-scientist.png"
identify -format "%f %wx%h %b\n" "$ROOT/13-sheet-human-scientist.png"
