import type { PresetSeed } from './types';

export const CAMERAS: PresetSeed[] = [
  {
    kind: 'camera',
    name: 'Island Overview',
    tags: ['camera', 'overview'],
    tier: 'play',
    params: {
      fov: 60,
      distance: 250,
      yaw: 0.78,
      pitch: 0.85,
      targetX: 0,
      targetY: 10,
      targetZ: 0,
    },
    doc: 'Sweeping panoramic vantage taking in the entirety of the volcanic atoll and open sea.',
  },
  {
    kind: 'camera',
    name: 'Beach Cam',
    tags: ['camera', 'tracking'],
    tier: 'play',
    params: {
      fov: 65,
      distance: 15,
      yaw: 1.57,
      pitch: 0.25,
      targetX: 45,
      targetY: 2,
      targetZ: -20,
    },
    doc: 'Low tracking perspective skimming right above the surf along the shoreline straightaway.',
  },
  {
    kind: 'camera',
    name: 'Cliff Top',
    tags: ['camera', 'scenic'],
    tier: 'build',
    params: {
      fov: 50,
      distance: 80,
      yaw: -1.2,
      pitch: 0.45,
      targetX: -30,
      targetY: 60,
      targetZ: 40,
    },
    doc: 'Perched high on the basalt ridge overlooking hair-raising hairpin drops.',
  },
  {
    kind: 'camera',
    name: 'Start Line',
    tags: ['camera', 'grid'],
    tier: 'play',
    params: {
      fov: 70,
      distance: 12,
      yaw: 0.0,
      pitch: 0.15,
      targetX: 0,
      targetY: 1.5,
      targetZ: -8,
    },
    doc: 'Dynamic head-on view of the revving starting grid before the horn blasts.',
  },
  {
    kind: 'camera',
    name: 'Hairpin',
    tags: ['camera', 'action'],
    tier: 'build',
    params: {
      fov: 75,
      distance: 18,
      yaw: 2.35,
      pitch: 0.35,
      targetX: 12,
      targetY: 4,
      targetZ: 85,
    },
    doc: 'Close-in angle capturing violent drift collisions through the volcano bend.',
  },
  {
    kind: 'camera',
    name: 'Top Down',
    tags: ['camera', 'tactical'],
    tier: 'play',
    params: {
      fov: 45,
      distance: 90,
      yaw: 0.0,
      pitch: 1.45,
      targetX: 0,
      targetY: 0,
      targetZ: 0,
    },
    doc: 'Direct bird-eye tactical perspective for analyzing racing lines and collision physics.',
  },
  {
    kind: 'camera',
    name: 'Low Rider',
    tags: ['camera', 'chase'],
    tier: 'play',
    params: {
      fov: 85,
      distance: 4.5,
      yaw: 3.14,
      pitch: 0.1,
      targetX: 0,
      targetY: 0.8,
      targetZ: 0,
    },
    doc: 'Adrenaline-fueled ground-skimming chase camera tight behind the goblin ball.',
  },
  {
    kind: 'camera',
    name: 'Cinematic',
    tags: ['camera', 'spectator'],
    tier: 'pro',
    params: {
      fov: 35,
      distance: 140,
      yaw: -0.65,
      pitch: 0.2,
      targetX: 10,
      targetY: 5,
      targetZ: 15,
    },
    doc: 'Telephoto broadcast angle creating high compression and dramatic racing drama.',
  },
];
