import type { PresetSeed } from './types';

export const MATERIALS: PresetSeed[] = [
  // 8 Metals
  {
    kind: 'material',
    name: 'Polished Gold',
    tags: ['metal', 'shiny', 'gold'],
    tier: 'play',
    params: { color: '#ffd700', roughness: 0.12, metalness: 0.98, repeat: 1, normalStrength: 0.8 },
    doc: 'High purity reflective gold alloy buffed to a radiant mirror sheen.',
  },
  {
    kind: 'material',
    name: 'Chrome Finish',
    tags: ['metal', 'shiny', 'chrome'],
    tier: 'play',
    params: { color: '#e8e8e8', roughness: 0.05, metalness: 0.98, repeat: 1, normalStrength: 0.5 },
    doc: 'Ultra-reflective specular chrome plating designed for speedster chassis trims.',
  },
  {
    kind: 'material',
    name: 'Raw Copper',
    tags: ['metal', 'copper', 'warm'],
    tier: 'build',
    params: { color: '#d97d58', roughness: 0.28, metalness: 0.92, repeat: 1, normalStrength: 1.0 },
    doc: 'Warm reddish raw copper with slight natural oxidation across the surface.',
  },
  {
    kind: 'material',
    name: 'Cast Iron',
    tags: ['metal', 'rough', 'dark'],
    tier: 'build',
    params: { color: '#383a3f', roughness: 0.65, metalness: 0.88, repeat: 1.5, normalStrength: 1.4 },
    doc: 'Heavy pitted cast iron with granular micro-relief and high density.',
  },
  {
    kind: 'material',
    name: 'Brushed Steel',
    tags: ['metal', 'brushed', 'steel'],
    tier: 'play',
    params: { color: '#b0b5be', roughness: 0.35, metalness: 0.95, repeat: 2.0, normalStrength: 1.1 },
    doc: 'Directionally milled stainless steel suited for sturdy mechanical components.',
  },
  {
    kind: 'material',
    name: 'Aged Brass',
    tags: ['metal', 'aged', 'brass'],
    tier: 'build',
    params: { color: '#c59b27', roughness: 0.40, metalness: 0.90, repeat: 1, normalStrength: 0.9 },
    doc: 'Antiqued golden-brown brass displaying subtle patina in shallow recesses.',
  },
  {
    kind: 'material',
    name: 'Anodized Titanium',
    tags: ['metal', 'smooth', 'alloy'],
    tier: 'build',
    params: { color: '#6f7482', roughness: 0.22, metalness: 0.92, repeat: 1, normalStrength: 0.7 },
    doc: 'Aerospace-grade titanium treated with a hard satin electrochemical layer.',
  },
  {
    kind: 'material',
    name: 'Rusted Iron',
    tags: ['metal', 'corroded', 'rust'],
    tier: 'build',
    params: { color: '#8a3324', roughness: 0.85, metalness: 0.60, repeat: 2.5, normalStrength: 2.2 },
    doc: 'Weathered scrap metal heavily encrusted with flaky iron oxide corrosion.',
  },

  // 10 Rough Stones and Soils
  {
    kind: 'material',
    name: 'Volcanic Basalt',
    tags: ['stone', 'volcanic', 'dark'],
    tier: 'play',
    params: { color: '#26292b', roughness: 0.86, metalness: 0.0, repeat: 2.0, normalStrength: 1.8 },
    doc: 'Dark igneous volcanic rock forming the island rugged cliffs and sharp crags.',
  },
  {
    kind: 'material',
    name: 'Porous Lava Rock',
    tags: ['stone', 'volcanic', 'rough'],
    tier: 'build',
    params: { color: '#3b2219', roughness: 0.92, metalness: 0.0, repeat: 3.0, normalStrength: 2.5 },
    doc: 'Vesicular cooled magma riddled with gas pockets and sharp abrasive edges.',
  },
  {
    kind: 'material',
    name: 'Mountain Granite',
    tags: ['stone', 'granite', 'mineral'],
    tier: 'build',
    params: { color: '#878789', roughness: 0.78, metalness: 0.0, repeat: 2.0, normalStrength: 1.3 },
    doc: 'Coarse-grained crystalline granite flecked with quartz and feldspar minerals.',
  },
  {
    kind: 'material',
    name: 'Dune Sandstone',
    tags: ['stone', 'sediment', 'warm'],
    tier: 'play',
    params: { color: '#d4a373', roughness: 0.82, metalness: 0.0, repeat: 1.5, normalStrength: 1.2 },
    doc: 'Layered warm sedimentary stone formed from ancient compressed beach dunes.',
  },
  {
    kind: 'material',
    name: 'Coral Limestone',
    tags: ['stone', 'coral', 'light'],
    tier: 'build',
    params: { color: '#ded0b6', roughness: 0.75, metalness: 0.0, repeat: 2.0, normalStrength: 1.4 },
    doc: 'Sun-bleached fossiliferous limestone studded with prehistoric reef fragments.',
  },
  {
    kind: 'material',
    name: 'Fine Volcanic Ash',
    tags: ['soil', 'volcanic', 'powdery'],
    tier: 'build',
    params: { color: '#4b4b4d', roughness: 0.90, metalness: 0.0, repeat: 1.0, normalStrength: 0.8 },
    doc: 'Loose powdery volcanic deposit that kicks up dramatic clouds during high-speed drifts.',
  },
  {
    kind: 'material',
    name: 'River Pebbles',
    tags: ['stone', 'smooth', 'river'],
    tier: 'build',
    params: { color: '#7d7065', roughness: 0.72, metalness: 0.0, repeat: 4.0, normalStrength: 1.9 },
    doc: 'Bed of rounded river gravel smoothed by rushing tropical mountain cascades.',
  },
  {
    kind: 'material',
    name: 'Tropical Mud',
    tags: ['soil', 'wet', 'earth'],
    tier: 'play',
    params: { color: '#3d2b1f', roughness: 0.76, metalness: 0.0, repeat: 1.5, normalStrength: 1.6 },
    doc: 'Dense slick rainforest mud that slows rolling goblin racers down to a crawl.',
  },
  {
    kind: 'material',
    name: 'Jungle Soil',
    tags: ['soil', 'organic', 'dark'],
    tier: 'build',
    params: { color: '#4a3728', roughness: 0.88, metalness: 0.0, repeat: 2.0, normalStrength: 1.2 },
    doc: 'Rich humus soil teeming with organic loam and fine root systems.',
  },
  {
    kind: 'material',
    name: 'Dark Island Slate',
    tags: ['stone', 'slate', 'mineral'],
    tier: 'build',
    params: { color: '#2f3542', roughness: 0.74, metalness: 0.0, repeat: 2.0, normalStrength: 1.1 },
    doc: 'Fine-grained foliated metamorphic slate ideal for sheer incline embankments.',
  },

  // 6 Sands and Shore Materials
  {
    kind: 'material',
    name: 'Golden Beach Sand',
    tags: ['sand', 'shore', 'tropical'],
    tier: 'play',
    params: { color: '#e3c07b', roughness: 0.84, metalness: 0.0, repeat: 3.0, normalStrength: 1.0 },
    doc: 'Fine sunlit coastal quartz sand offering medium grip along lagoon turns.',
  },
  {
    kind: 'material',
    name: 'Wet Shore Sand',
    tags: ['sand', 'wet', 'shore'],
    tier: 'play',
    params: { color: '#9c7a4b', roughness: 0.38, metalness: 0.0, repeat: 2.0, normalStrength: 0.6 },
    doc: 'Compacted water-saturated sand right at the wave break with glossy light reflection.',
  },
  {
    kind: 'material',
    name: 'Windswept Dunes',
    tags: ['sand', 'dunes', 'warm'],
    tier: 'build',
    params: { color: '#ecc88a', roughness: 0.89, metalness: 0.0, repeat: 4.0, normalStrength: 1.7 },
    doc: 'Deep loose sand ripples sculpted by offshore tradewinds across the open hills.',
  },
  {
    kind: 'material',
    name: 'Crushed Shell Sand',
    tags: ['sand', 'shell', 'shore'],
    tier: 'build',
    params: { color: '#f3e9d2', roughness: 0.73, metalness: 0.0, repeat: 3.0, normalStrength: 1.5 },
    doc: 'Bright littoral sediment packed with iridescent shards of crushed mollusks.',
  },
  {
    kind: 'material',
    name: 'Pink Coral Sand',
    tags: ['sand', 'coral', 'pink'],
    tier: 'play',
    params: { color: '#e8b4b8', roughness: 0.77, metalness: 0.0, repeat: 2.5, normalStrength: 1.1 },
    doc: 'Rare pastel beach sand tinted by microscopic red organisms and broken coral.',
  },
  {
    kind: 'material',
    name: 'Tidal Mud Flat',
    tags: ['shore', 'wet', 'coastal'],
    tier: 'build',
    params: { color: '#635343', roughness: 0.52, metalness: 0.0, repeat: 1.5, normalStrength: 0.9 },
    doc: 'Low tide estuary silt leaving a slippery semi-gloss coating over the track.',
  },

  // 6 Plants
  {
    kind: 'material',
    name: 'Tropical Grass',
    tags: ['plant', 'foliage', 'green'],
    tier: 'play',
    params: { color: '#4f8a10', roughness: 0.60, metalness: 0.0, repeat: 3.0, normalStrength: 1.2 },
    doc: 'Lush tropical grass blades providing soft cushioning for rogue downhill rolls.',
  },
  {
    kind: 'material',
    name: 'Island Moss',
    tags: ['plant', 'moss', 'forest'],
    tier: 'play',
    params: { color: '#2d5a27', roughness: 0.85, metalness: 0.0, repeat: 3.0, normalStrength: 1.7 },
    doc: 'Velvety carpet of emerald bryophytes blanketing shaded damp rock outcrops.',
  },
  {
    kind: 'material',
    name: 'Waxy Palm Leaf',
    tags: ['plant', 'waxy', 'foliage'],
    tier: 'build',
    params: { color: '#23532f', roughness: 0.32, metalness: 0.0, repeat: 1.0, normalStrength: 0.8 },
    doc: 'Glossy cuticular surface of wide palm fronds filtering radiant canopy sunlight.',
  },
  {
    kind: 'material',
    name: 'Jungle Floor Leaf',
    tags: ['plant', 'organic', 'jungle'],
    tier: 'build',
    params: { color: '#3a3d24', roughness: 0.79, metalness: 0.0, repeat: 2.5, normalStrength: 1.4 },
    doc: 'Dense bed of decayed deciduous leaves and decaying twigs on rainforest trails.',
  },
  {
    kind: 'material',
    name: 'Bright Banana Leaf',
    tags: ['plant', 'leaf', 'tropical'],
    tier: 'play',
    params: { color: '#6cae2a', roughness: 0.28, metalness: 0.0, repeat: 1.0, normalStrength: 0.9 },
    doc: 'Huge flexible emerald leaves with satin sheen used for makeshift goblin gliders.',
  },
  {
    kind: 'material',
    name: 'Dry Thatch',
    tags: ['plant', 'thatch', 'straw'],
    tier: 'build',
    params: { color: '#a88548', roughness: 0.83, metalness: 0.0, repeat: 3.5, normalStrength: 1.8 },
    doc: 'Sun-dried palm fronds bundled into durable roofing for tropical track obstacles.',
  },

  // 6 Glossy Plastics/Paints
  {
    kind: 'material',
    name: 'Candy Red Paint',
    tags: ['plastic', 'glossy', 'paint'],
    tier: 'play',
    params: { color: '#e6194b', roughness: 0.24, metalness: 0.04, repeat: 1, normalStrength: 0.4 },
    doc: 'Vibrant racing coat with a gleaming clear lacquer coat over deep crimson tint.',
  },
  {
    kind: 'material',
    name: 'Goblin Green Gloss',
    tags: ['plastic', 'glossy', 'paint'],
    tier: 'play',
    params: { color: '#3cb44b', roughness: 0.26, metalness: 0.02, repeat: 1, normalStrength: 0.4 },
    doc: 'Electric toxic green gloss engineered specifically for mischievous speed fiends.',
  },
  {
    kind: 'material',
    name: 'Banana Yellow Gloss',
    tags: ['plastic', 'glossy', 'paint'],
    tier: 'play',
    params: { color: '#ffe119', roughness: 0.22, metalness: 0.02, repeat: 1, normalStrength: 0.3 },
    doc: 'High-visibility safety enamel applied to checkpoint markers and warning bollards.',
  },
  {
    kind: 'material',
    name: 'Ocean Blue Lacquer',
    tags: ['plastic', 'glossy', 'paint'],
    tier: 'play',
    params: { color: '#4363d8', roughness: 0.25, metalness: 0.05, repeat: 1, normalStrength: 0.4 },
    doc: 'Deep cerulean gloss enamel reflecting the vivid tropical waters of the archipelago.',
  },
  {
    kind: 'material',
    name: 'Hot Pink Enamel',
    tags: ['plastic', 'glossy', 'paint'],
    tier: 'play',
    params: { color: '#f032e6', roughness: 0.28, metalness: 0.03, repeat: 1, normalStrength: 0.4 },
    doc: 'Flamboyant fluorescent resin finish that demands attention at the finish line.',
  },
  {
    kind: 'material',
    name: 'Midnight Purple Gloss',
    tags: ['plastic', 'glossy', 'paint'],
    tier: 'play',
    params: { color: '#911eb4', roughness: 0.30, metalness: 0.04, repeat: 1, normalStrength: 0.4 },
    doc: 'Moody chromatic purple plastic with deep specular highlights under sunbeams.',
  },

  // 4 Rubber/Tyre/Cloth
  {
    kind: 'material',
    name: 'Racing Tyre Rubber',
    tags: ['rubber', 'elastic', 'dark'],
    tier: 'play',
    params: { color: '#1b1c1e', roughness: 0.62, metalness: 0.0, repeat: 2.0, normalStrength: 1.5 },
    doc: 'Vulcanized high-grip tread compound engineered for violent cornering g-forces.',
  },
  {
    kind: 'material',
    name: 'Bumper Pad Foam',
    tags: ['rubber', 'cushion', 'foam'],
    tier: 'build',
    params: { color: '#ff6b35', roughness: 0.55, metalness: 0.0, repeat: 1.0, normalStrength: 0.9 },
    doc: 'High-density closed-cell ethylene foam designed to absorb crushing ball impacts.',
  },
  {
    kind: 'material',
    name: 'Island Sail Canvas',
    tags: ['cloth', 'woven', 'fabric'],
    tier: 'build',
    params: { color: '#f0ede1', roughness: 0.82, metalness: 0.0, repeat: 4.0, normalStrength: 1.3 },
    doc: 'Heavy tightly-woven nautical hemp cloth used for island finish banners.',
  },
  {
    kind: 'material',
    name: 'Woven Hemp Rope',
    tags: ['cloth', 'hemp', 'fiber'],
    tier: 'build',
    params: { color: '#8d7b68', roughness: 0.90, metalness: 0.0, repeat: 3.0, normalStrength: 2.0 },
    doc: 'Braided plant fibers coiled into rugged barrier ropes along cliff edges.',
  },

  // 4 Wood Types
  {
    kind: 'material',
    name: 'Driftwood Timber',
    tags: ['wood', 'weathered', 'natural'],
    tier: 'play',
    params: { color: '#a39281', roughness: 0.70, metalness: 0.0, repeat: 2.0, normalStrength: 1.2 },
    doc: 'Salt-bleached maritime timber washed ashore onto the coral breakwaters.',
  },
  {
    kind: 'material',
    name: 'Bamboo Stalk',
    tags: ['wood', 'smooth', 'plant'],
    tier: 'play',
    params: { color: '#8f9e47', roughness: 0.35, metalness: 0.0, repeat: 1.5, normalStrength: 0.7 },
    doc: 'Hard glossy siliceous outer skin of giant hollow tropical bamboo poles.',
  },
  {
    kind: 'material',
    name: 'Tropical Teak',
    tags: ['wood', 'polished', 'teak'],
    tier: 'build',
    params: { color: '#5c3a21', roughness: 0.48, metalness: 0.0, repeat: 2.0, normalStrength: 0.9 },
    doc: 'Oily water-resistant hardwood prized for carved tribal decorations.',
  },
  {
    kind: 'material',
    name: 'Charred Koa Wood',
    tags: ['wood', 'charred', 'dark'],
    tier: 'build',
    params: { color: '#211815', roughness: 0.68, metalness: 0.0, repeat: 2.5, normalStrength: 1.5 },
    doc: 'Fire-tempered native island wood showing dark grain structure and scorched texture.',
  },

  // 4 Special
  {
    kind: 'material',
    name: 'Glacial Ice',
    tags: ['special', 'ice', 'translucent'],
    tier: 'play',
    params: { color: '#bce6eb', roughness: 0.08, metalness: 0.02, repeat: 1.0, normalStrength: 0.3 },
    doc: 'Pristine slick frozen water offering frictionless gliding across winter courses.',
  },
  {
    kind: 'material',
    name: 'Volcanic Obsidian',
    tags: ['special', 'obsidian', 'glass'],
    tier: 'play',
    params: { color: '#121214', roughness: 0.15, metalness: 0.02, repeat: 1.0, normalStrength: 0.5 },
    doc: 'Extrusive black volcanic glass with razor sharp conchoidal fracture rims.',
  },
  {
    kind: 'material',
    name: 'Fossilized Amber',
    tags: ['special', 'amber', 'gem'],
    tier: 'build',
    params: { color: '#d97706', roughness: 0.20, metalness: 0.01, repeat: 1.0, normalStrength: 0.4 },
    doc: 'Translucent fossilized tree resin with a honey glow and trapped prehistoric air bubbles.',
  },
  {
    kind: 'material',
    name: 'Carved Imperial Jade',
    tags: ['special', 'jade', 'mineral'],
    tier: 'play',
    params: { color: '#1b7a4d', roughness: 0.26, metalness: 0.02, repeat: 1.0, normalStrength: 0.6 },
    doc: 'Polished nephrite jade stone carved into sacred lucky amulets by goblin shamans.',
  },
];
