import type { PresetSeed } from './types';

export const PROPS: PresetSeed[] = [
  {
    kind: 'entity',
    name: 'Traffic Cone',
    tags: ['prop', 'hazard', 'track'],
    tier: 'play',
    params: {
      shape: 'cylinder',
      size: 0.8,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 0.4,
      scaleY: 1.4,
      scaleZ: 0.4,
      body: 'static',
      mass: 5,
      friction: 0.6,
      restitution: 0.2,
      visible: true,
    },
    refs: { material: 'Banana Yellow Gloss' },
    doc: 'Bright marker cone guiding goblins away from dangerous chasm edges.',
  },
  {
    kind: 'entity',
    name: 'Cargo Barrel',
    tags: ['prop', 'obstacle', 'wood'],
    tier: 'play',
    params: {
      shape: 'cylinder',
      size: 1.2,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 0.8,
      scaleY: 1.2,
      scaleZ: 0.8,
      body: 'static',
      mass: 40,
      friction: 0.7,
      restitution: 0.3,
      visible: true,
    },
    refs: { material: 'Tropical Teak' },
    doc: 'Sturdy tropical wood barrel packed with fermented swamp fruit.',
  },
  {
    kind: 'entity',
    name: 'Wooden Crate',
    tags: ['prop', 'obstacle', 'storage'],
    tier: 'play',
    params: {
      shape: 'box',
      size: 1.5,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 1.0,
      scaleY: 1.0,
      scaleZ: 1.0,
      body: 'static',
      mass: 30,
      friction: 0.8,
      restitution: 0.1,
      visible: true,
    },
    refs: { material: 'Driftwood Timber' },
    doc: 'Weathered salvage crate stacked along straight sections of the course.',
  },
  {
    kind: 'entity',
    name: 'Finish Arch Pillar',
    tags: ['prop', 'structure', 'stone'],
    tier: 'build',
    params: {
      shape: 'box',
      size: 3.5,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 0.8,
      scaleY: 4.0,
      scaleZ: 0.8,
      body: 'static',
      mass: 500,
      friction: 0.9,
      restitution: 0.1,
      visible: true,
    },
    refs: { material: 'Mountain Granite' },
    doc: 'Monolithic granite column anchoring the checkered finish banner.',
  },
  {
    kind: 'entity',
    name: 'Cast Iron Bollard',
    tags: ['prop', 'barrier', 'metal'],
    tier: 'build',
    params: {
      shape: 'cylinder',
      size: 1.0,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 0.3,
      scaleY: 1.1,
      scaleZ: 0.3,
      body: 'static',
      mass: 120,
      friction: 0.7,
      restitution: 0.4,
      visible: true,
    },
    refs: { material: 'Cast Iron' },
    doc: 'Heavy mooring bollard preventing runaway racers from plunging into the sea.',
  },
  {
    kind: 'entity',
    name: 'Racing Tyre Stack',
    tags: ['prop', 'barrier', 'rubber'],
    tier: 'play',
    params: {
      shape: 'cylinder',
      size: 1.6,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 1.0,
      scaleY: 1.8,
      scaleZ: 1.0,
      body: 'static',
      mass: 80,
      friction: 0.95,
      restitution: 0.7,
      visible: true,
    },
    refs: { material: 'Racing Tyre Rubber' },
    doc: 'Cushioning tyre barrier erected around high-speed hairpin curves.',
  },
  {
    kind: 'entity',
    name: 'Tiki Totem Post',
    tags: ['prop', 'tribal', 'wood'],
    tier: 'play',
    params: {
      shape: 'cylinder',
      size: 2.5,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 0.5,
      scaleY: 2.8,
      scaleZ: 0.5,
      body: 'static',
      mass: 90,
      friction: 0.75,
      restitution: 0.2,
      visible: true,
    },
    refs: { material: 'Charred Koa Wood' },
    doc: 'Carved wooden island guardian watching silently over the goblin track.',
  },
  {
    kind: 'entity',
    name: 'Volcanic Boulder',
    tags: ['prop', 'obstacle', 'nature'],
    tier: 'play',
    params: {
      shape: 'sphere',
      size: 2.2,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 1.2,
      scaleY: 1.0,
      scaleZ: 1.1,
      body: 'static',
      mass: 350,
      friction: 0.85,
      restitution: 0.15,
      visible: true,
    },
    refs: { material: 'Volcanic Basalt' },
    doc: 'Gigantic igneous rock dislodged from the caldera during the last eruption.',
  },
  {
    kind: 'entity',
    name: 'Fallen Palm Log',
    tags: ['prop', 'obstacle', 'nature'],
    tier: 'play',
    params: {
      shape: 'cylinder',
      size: 2.8,
      x: 0,
      y: 0,
      z: 0,
      yaw: 1.57,
      scaleX: 0.5,
      scaleY: 3.2,
      scaleZ: 0.5,
      body: 'static',
      mass: 75,
      friction: 0.8,
      restitution: 0.2,
      visible: true,
    },
    refs: { material: 'Driftwood Timber' },
    doc: 'Fallen jungle trunk acting as an impromptu ramp or obstacle hurdle.',
  },
  {
    kind: 'entity',
    name: 'Grandstand Bench',
    tags: ['prop', 'furniture', 'wood'],
    tier: 'build',
    params: {
      shape: 'box',
      size: 2.0,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 2.5,
      scaleY: 0.5,
      scaleZ: 0.8,
      body: 'static',
      mass: 30,
      friction: 0.65,
      restitution: 0.1,
      visible: true,
    },
    refs: { material: 'Bamboo Stalk' },
    doc: 'Bamboo bleacher seating where goblin spectators wager their shiny trinkets.',
  },
  {
    kind: 'entity',
    name: 'Checkered Flag Pole',
    tags: ['prop', 'landmark', 'metal'],
    tier: 'build',
    params: {
      shape: 'cylinder',
      size: 4.0,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 0.1,
      scaleY: 4.5,
      scaleZ: 0.1,
      body: 'static',
      mass: 45,
      friction: 0.5,
      restitution: 0.2,
      visible: true,
    },
    refs: { material: 'Brushed Steel' },
    doc: 'Slender stainless steel mast waving the celebratory checkered pennant.',
  },
  {
    kind: 'entity',
    name: 'Corner Bumper Pad',
    tags: ['prop', 'safety', 'foam'],
    tier: 'play',
    params: {
      shape: 'box',
      size: 1.8,
      x: 0,
      y: 0,
      z: 0,
      yaw: 0,
      scaleX: 2.0,
      scaleY: 1.0,
      scaleZ: 0.5,
      body: 'static',
      mass: 25,
      friction: 0.6,
      restitution: 0.85,
      visible: true,
    },
    refs: { material: 'Bumper Pad Foam' },
    doc: 'Shock-absorbing protective foam mattress mounted at high-impact crash walls.',
  },
];
