import type { PresetSeed } from './types';

export const RACERS: PresetSeed[] = [
  {
    kind: 'racer',
    name: 'Grubnik Bonecrusher',
    tags: ['goblin', 'heavy', 'bruiser'],
    tier: 'play',
    params: {
      weight: 9,
      speed: 4,
      bounce: 2,
      color: '#2f4f2f',
      accent: '#ffd700',
      skill: 0.75,
      hat: 'helmet',
      ears: 'pointy',
    },
    doc: 'A mountain of muscle who clears racing lanes by violently crushing into anything smaller than him.',
  },
  {
    kind: 'racer',
    name: 'Snaga Quickfingers',
    tags: ['goblin', 'fast', 'speedster'],
    tier: 'play',
    params: {
      weight: 2,
      speed: 10,
      bounce: 3,
      color: '#7cfc00',
      accent: '#191970',
      skill: 0.92,
      hat: 'bandana',
      ears: 'big',
    },
    doc: 'Stole a prototype rocket ball engine and taped down the throttle lever with sticky mangrove sap.',
  },
  {
    kind: 'racer',
    name: 'Boingo Bogtrotter',
    tags: ['goblin', 'bouncy', 'daredevil'],
    tier: 'play',
    params: {
      weight: 3,
      speed: 3,
      bounce: 9,
      color: '#20b2aa',
      accent: '#ffff00',
      skill: 0.60,
      hat: 'pot',
      ears: 'floppy',
    },
    doc: 'Spends more time bouncing hundreds of feet in the air than actually making contact with the racetrack.',
  },
  {
    kind: 'racer',
    name: 'Gorg the Anchor',
    tags: ['goblin', 'heavy', 'tank'],
    tier: 'build',
    params: {
      weight: 10,
      speed: 3,
      bounce: 2,
      color: '#4a3525',
      accent: '#00ffff',
      skill: 0.45,
      hat: 'pot',
      ears: 'small',
    },
    doc: 'So heavy he regularly leaves permanent craters in wooden suspension bridges across the lagoon.',
  },
  {
    kind: 'racer',
    name: 'Zippy Sparkfuse',
    tags: ['goblin', 'fast', 'scout'],
    tier: 'play',
    params: {
      weight: 2,
      speed: 9,
      bounce: 4,
      color: '#32cd32',
      accent: '#4b0082',
      skill: 0.88,
      hat: 'cap',
      ears: 'pointy',
    },
    doc: 'Believes brakes are an unnecessary technical complication invented by cowards and bureaucrats.',
  },
  {
    kind: 'racer',
    name: 'Bouncer McSqueak',
    tags: ['goblin', 'bouncy', 'spring'],
    tier: 'play',
    params: {
      weight: 1,
      speed: 4,
      bounce: 10,
      color: '#8a2be2',
      accent: '#7fff00',
      skill: 0.22,
      hat: 'none',
      ears: 'floppy',
    },
    doc: 'A chaotic bundle of energy who bounces completely out of the race stadium twice every weekend.',
  },
  {
    kind: 'racer',
    name: 'Krag Rollmaster',
    tags: ['goblin', 'balanced', 'veteran'],
    tier: 'play',
    params: {
      weight: 5,
      speed: 5,
      bounce: 5,
      color: '#556b2f',
      accent: '#ff8c00',
      skill: 0.70,
      hat: 'helmet',
      ears: 'pointy',
    },
    doc: 'A steady island racing champion who relies on calm steering rather than reckless explosive boosts.',
  },
  {
    kind: 'racer',
    name: 'Nixie Wavecrest',
    tags: ['goblin', 'balanced', 'coastal'],
    tier: 'play',
    params: {
      weight: 4,
      speed: 6,
      bounce: 5,
      color: '#008b8b',
      accent: '#ffe14d',
      skill: 0.82,
      hat: 'leaf',
      ears: 'big',
    },
    doc: 'Harnesses tidal wave crests and sea breezes to surf over jagged barrier reef shortcuts.',
  },
  {
    kind: 'racer',
    name: 'Stumpy Ironbelly',
    tags: ['goblin', 'balanced', 'brawler'],
    tier: 'build',
    params: {
      weight: 6,
      speed: 5,
      bounce: 4,
      color: '#5c5042',
      accent: '#adff2f',
      skill: 0.55,
      hat: 'horns',
      ears: 'small',
    },
    doc: 'Known for laughing hysterically whenever another racer tries to ram his reinforced iron sphere.',
  },
  {
    kind: 'racer',
    name: 'Baron Von Gob',
    tags: ['goblin', 'balanced', 'royal'],
    tier: 'pro',
    params: {
      weight: 4,
      speed: 7,
      bounce: 4,
      color: '#9932cc',
      accent: '#ffd700',
      skill: 0.85,
      hat: 'crown',
      ears: 'pointy',
    },
    doc: 'Self-proclaimed monarch of the volcanic caldera who races solely for bragging rights and shiny loot.',
  },
  {
    kind: 'racer',
    name: 'Gimble Driftleaf',
    tags: ['goblin', 'balanced', 'scavenger'],
    tier: 'play',
    params: {
      weight: 4,
      speed: 4,
      bounce: 6,
      color: '#8fbc8f',
      accent: '#1a0033',
      skill: 0.38,
      hat: 'leaf',
      ears: 'big',
    },
    doc: 'Constructed his racing ball out of driftwood salvaged from shipwreck cove and coconut shells.',
  },
  {
    kind: 'racer',
    name: 'Skitter Rustfang',
    tags: ['goblin', 'balanced', 'tinkerer'],
    tier: 'build',
    params: {
      weight: 5,
      speed: 6,
      bounce: 3,
      color: '#69823e',
      accent: '#ffffff',
      skill: 0.65,
      hat: 'bandana',
      ears: 'floppy',
    },
    doc: 'Never enters a race without at least five smuggled spanners and a pocketful of explosive grease.',
  },
];
