import { normalizeSetup } from './normalize';
import type { LightSetup } from './types';

/**
 * The lighting library: eighteen art-directed setups written by an Arena model for the Light Lab and then taken in as presets.
 * Each one is run through normalizeSetup, so every entry is legal by construction. Lamps hang on named props (lantern, torch, campfire, barrel)
 * or on the point of interest ('focus'); the scene decides where those are.
 */
const N = '#808080'; // neutral grade colour

const RAW: readonly unknown[] = [
  {
    id: 'noon-clear',
    name: 'Noon Clear',
    sun: { color: '#fff4e2', intensity: 3.3, azimuthDeg: 35, elevationDeg: 68, shadowSoftness: 1.4, shadowMapSize: 2048 },
    hemi: { sky: '#a6d6ff', ground: '#d9c595', intensity: 0.95 },
    ambient: { color: '#ffffff', intensity: 0.06 },
    sky: { top: '#2a78dc', horizon: '#bfe5ff', bottom: '#dcf2ff', sunGlow: 0.6 },
    fog: { color: '#cfe7f4', density: 0.0055 },
    water: { color: '#16a3b6', opacity: 0.8, roughness: 0.08 },
    toneMapping: 'aces',
    exposure: 1.0,
    post: {
      bloom: { strength: 0.15, radius: 0.4, threshold: 1.25 },
      vignette: { darkness: 0.25, offset: 0.55 },
      saturation: 1.08,
      contrast: 1.04,
      lift: N,
      gamma: N,
      gain: N,
      ssao: { enabled: true, radius: 1.0, intensity: 1.0 },
      fxaa: true,
      grain: 0.008,
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    sun: { color: '#ffb25a', intensity: 3.5, azimuthDeg: 250, elevationDeg: 13, shadowSoftness: 2, shadowMapSize: 4096 },
    hemi: { sky: '#ffd8a8', ground: '#5e4838', intensity: 0.7 },
    ambient: { color: '#ffe0c0', intensity: 0.05 },
    fill: { color: '#7fa6ff', intensity: 0.35, position: [-10, 6, 8] },
    sky: { top: '#4a70b6', horizon: '#ffcd86', bottom: '#f6b478', sunGlow: 1.4 },
    fog: { color: '#f3c693', density: 0.009 },
    water: { color: '#2a8898', opacity: 0.85, roughness: 0.1 },
    toneMapping: 'agx',
    exposure: 1.2,
    post: {
      bloom: { strength: 0.35, radius: 0.6, threshold: 0.9 },
      vignette: { darkness: 0.35, offset: 0.45 },
      saturation: 1.14,
      contrast: 1.06,
      lift: '#7c7d88',
      gamma: '#82807c',
      gain: '#8a8178',
      ssao: { enabled: true, radius: 1.2, intensity: 1.0 },
      fxaa: true,
      grain: 0.015,
    },
  },
  {
    id: 'sunset-blaze',
    name: 'Sunset Blaze',
    sun: { color: '#ff6526', intensity: 3.2, azimuthDeg: 272, elevationDeg: 4, shadowSoftness: 2.6, shadowMapSize: 4096 },
    hemi: { sky: '#ff8a6c', ground: '#3b2342', intensity: 0.6 },
    ambient: { color: '#ff9a80', intensity: 0.05 },
    fill: { color: '#5a4ad6', intensity: 0.55, position: [-8, 5, -6] },
    sky: { top: '#29286a', horizon: '#ff7638', bottom: '#ff4a4e', sunGlow: 2.2 },
    fog: { color: '#e7725a', density: 0.012 },
    water: { color: '#3a4c8a', opacity: 0.88, roughness: 0.06 },
    toneMapping: 'aces',
    exposure: 1.25,
    post: {
      bloom: { strength: 0.6, radius: 0.7, threshold: 0.8 },
      vignette: { darkness: 0.5, offset: 0.4 },
      saturation: 1.2,
      contrast: 1.1,
      lift: '#7c7a8c',
      gamma: N,
      gain: '#8e8078',
      ssao: { enabled: true, radius: 1.2, intensity: 0.9 },
      fxaa: true,
      grain: 0.02,
    },
  },
  {
    id: 'tropical-dawn',
    name: 'Tropical Dawn',
    sun: { color: '#ffc4a0', intensity: 2.3, azimuthDeg: 95, elevationDeg: 9, shadowSoftness: 3, shadowMapSize: 2048 },
    hemi: { sky: '#b8c6ff', ground: '#e6b4a6', intensity: 0.95 },
    ambient: { color: '#f2d6ff', intensity: 0.08 },
    fill: { color: '#ffd0e0', intensity: 0.3, position: [8, 4, -8] },
    sky: { top: '#6a8ed8', horizon: '#ffc1ae', bottom: '#ffd8c0', sunGlow: 1.3 },
    fog: { color: '#f4cdc2', density: 0.014 },
    water: { color: '#4cb2c2', opacity: 0.78, roughness: 0.1 },
    toneMapping: 'agx',
    exposure: 1.3,
    post: {
      bloom: { strength: 0.4, radius: 0.8, threshold: 0.85 },
      vignette: { darkness: 0.2, offset: 0.5 },
      saturation: 1.06,
      contrast: 0.98,
      lift: '#84808c',
      gamma: '#82808a',
      gain: '#888084',
      ssao: { enabled: true, radius: 1.1, intensity: 0.9 },
      fxaa: true,
      grain: 0.012,
    },
  },
  {
    id: 'overcast',
    name: 'Overcast',
    sun: { color: '#e6ecf2', intensity: 0.9, azimuthDeg: 60, elevationDeg: 55, shadowSoftness: 9, shadowMapSize: 1024 },
    hemi: { sky: '#dae1e7', ground: '#8b897d', intensity: 1.6 },
    ambient: { color: '#ffffff', intensity: 0.15 },
    sky: { top: '#97a3ad', horizon: '#c8ced2', bottom: '#cfd3d4', sunGlow: 0.1 },
    fog: { color: '#c2c8cb', density: 0.02 },
    water: { color: '#5b888d', opacity: 0.9, roughness: 0.25 },
    toneMapping: 'neutral',
    exposure: 1.1,
    post: {
      bloom: { strength: 0.05, radius: 0.3, threshold: 1.5 },
      vignette: { darkness: 0.2, offset: 0.5 },
      saturation: 0.85,
      contrast: 0.96,
      lift: '#828486',
      gamma: N,
      gain: '#808285',
      ssao: { enabled: true, radius: 1.4, intensity: 1.25 },
      fxaa: true,
      grain: 0.012,
    },
  },
  {
    id: 'storm-front',
    name: 'Storm Front',
    sun: { color: '#b8c4d6', intensity: 1.7, azimuthDeg: 200, elevationDeg: 22, shadowSoftness: 3, shadowMapSize: 2048 },
    hemi: { sky: '#4a5868', ground: '#2a2f2a', intensity: 0.9 },
    ambient: { color: '#8899aa', intensity: 0.06 },
    fill: { color: '#c9e4ff', intensity: 0.7, position: [-6, 10, -8] },
    sky: { top: '#1b222c', horizon: '#58646d', bottom: '#394047', sunGlow: 0.25 },
    fog: { color: '#47515a', density: 0.03 },
    water: { color: '#21373b', opacity: 0.94, roughness: 0.18 },
    toneMapping: 'aces',
    exposure: 1.05,
    post: {
      bloom: { strength: 0.2, radius: 0.5, threshold: 1.0 },
      vignette: { darkness: 0.65, offset: 0.35 },
      saturation: 0.7,
      contrast: 1.18,
      lift: '#7e8287',
      gamma: '#7c8088',
      gain: '#7e8084',
      ssao: { enabled: true, radius: 1.2, intensity: 1.3 },
      fxaa: true,
      grain: 0.035,
    },
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    sun: { color: '#8fa8ff', intensity: 0.75, azimuthDeg: 280, elevationDeg: 6, shadowSoftness: 5, shadowMapSize: 2048 },
    hemi: { sky: '#4d6bc7', ground: '#1c2236', intensity: 1.0 },
    ambient: { color: '#6c80c8', intensity: 0.08 },
    extraLights: [
      { type: 'point', color: '#ffb066', intensity: 7, anchor: 'lantern', offset: [0, 0, 0], distance: 9 },
      { type: 'point', color: '#ffa04a', intensity: 6, anchor: 'torch', offset: [0, 0, 0], distance: 7 },
    ],
    sky: { top: '#0e1e4e', horizon: '#5979cf', bottom: '#29346f', sunGlow: 0.6 },
    fog: { color: '#394e8e', density: 0.016 },
    water: { color: '#1a3466', opacity: 0.9, roughness: 0.07 },
    toneMapping: 'agx',
    exposure: 1.45,
    post: {
      bloom: { strength: 0.5, radius: 0.7, threshold: 0.6 },
      vignette: { darkness: 0.45, offset: 0.4 },
      saturation: 1.05,
      contrast: 1.04,
      lift: '#7c7e8c',
      gamma: '#7e8088',
      gain: '#808088',
      ssao: { enabled: true, radius: 1.1, intensity: 1.0 },
      fxaa: true,
      grain: 0.02,
    },
  },
  {
    id: 'moonlit-night',
    name: 'Moonlit Night',
    sun: { color: '#9db8ff', intensity: 0.95, azimuthDeg: 140, elevationDeg: 38, shadowSoftness: 2.5, shadowMapSize: 2048 },
    hemi: { sky: '#1e2d55', ground: '#0a0d14', intensity: 0.5 },
    ambient: { color: '#3a4a7a', intensity: 0.05 },
    fill: { color: '#6b88d6', intensity: 0.25, position: [-8, 6, -10] },
    extraLights: [{ type: 'point', color: '#ffcf8a', intensity: 3, anchor: 'lantern', offset: [0, 0, 0], distance: 6 }],
    sky: { top: '#040a1c', horizon: '#1a2b55', bottom: '#0b1328', sunGlow: 0.9 },
    fog: { color: '#0f1a33', density: 0.018 },
    water: { color: '#0d1e3d', opacity: 0.92, roughness: 0.05 },
    toneMapping: 'aces',
    exposure: 1.55,
    post: {
      bloom: { strength: 0.6, radius: 0.6, threshold: 0.5 },
      vignette: { darkness: 0.55, offset: 0.35 },
      saturation: 0.8,
      contrast: 1.08,
      lift: '#7c7e8a',
      gamma: '#7c7e8a',
      gain: '#7c8090',
      ssao: { enabled: true, radius: 1.0, intensity: 0.8 },
      fxaa: true,
      grain: 0.03,
    },
  },
  {
    id: 'volcanic-ash',
    name: 'Volcanic Ash',
    sun: { color: '#ff7a3a', intensity: 2.2, azimuthDeg: 320, elevationDeg: 18, shadowSoftness: 4, shadowMapSize: 2048 },
    hemi: { sky: '#6e3a2a', ground: '#1a0d0a', intensity: 0.7 },
    ambient: { color: '#803020', intensity: 0.06 },
    fill: { color: '#ff3b1a', intensity: 0.7, position: [-4, 2, -10] },
    extraLights: [{ type: 'point', color: '#ff4a1a', intensity: 14, anchor: 'campfire', offset: [0, 0, 0], distance: 10 }],
    sky: { top: '#1e1414', horizon: '#b44a24', bottom: '#401814', sunGlow: 1.6 },
    fog: { color: '#6a3424', density: 0.028 },
    water: { color: '#2a1e1e', opacity: 0.95, roughness: 0.3 },
    toneMapping: 'aces',
    exposure: 1.2,
    post: {
      bloom: { strength: 0.7, radius: 0.8, threshold: 0.7 },
      vignette: { darkness: 0.6, offset: 0.35 },
      saturation: 1.1,
      contrast: 1.15,
      lift: '#868078',
      gamma: '#84807a',
      gain: '#8a7e76',
      ssao: { enabled: true, radius: 1.3, intensity: 1.1 },
      fxaa: true,
      grain: 0.04,
    },
  },
  {
    id: 'neon-dusk',
    name: 'Neon Dusk',
    sun: { color: '#8a5cff', intensity: 0.6, azimuthDeg: 300, elevationDeg: 7, shadowSoftness: 4, shadowMapSize: 2048 },
    hemi: { sky: '#4b2a8a', ground: '#0e2a3a', intensity: 0.7 },
    ambient: { color: '#3a2266', intensity: 0.05 },
    fill: { color: '#00e5ff', intensity: 1.3, position: [-9, 4, -6] },
    extraLights: [
      { type: 'point', color: '#ff2bd6', intensity: 20, anchor: 'focus', offset: [-2.2, 0.4, 1.2], distance: 10 },
      { type: 'point', color: '#19e3ff', intensity: 20, anchor: 'focus', offset: [2.2, 0.2, 0.6], distance: 10 },
      { type: 'spot', color: '#ff4fd8', intensity: 60, anchor: 'lantern', offset: [-1, 4, 1], distance: 16 },
    ],
    sky: { top: '#120a2e', horizon: '#ff3caa', bottom: '#2b0f4f', sunGlow: 1.1 },
    fog: { color: '#3a1a5e', density: 0.02 },
    water: { color: '#14204a', opacity: 0.9, roughness: 0.05 },
    toneMapping: 'aces',
    exposure: 1.3,
    post: {
      bloom: { strength: 0.9, radius: 0.75, threshold: 0.55 },
      vignette: { darkness: 0.55, offset: 0.4 },
      saturation: 1.25,
      contrast: 1.1,
      lift: '#80788c',
      gamma: '#807c88',
      gain: '#84808a',
      ssao: { enabled: true, radius: 1.0, intensity: 1.0 },
      fxaa: true,
      grain: 0.025,
    },
  },
  {
    id: 'foggy-morning',
    name: 'Foggy Morning',
    sun: { color: '#fff0d4', intensity: 1.5, azimuthDeg: 110, elevationDeg: 16, shadowSoftness: 6, shadowMapSize: 2048 },
    hemi: { sky: '#e8ece6', ground: '#a7a68f', intensity: 1.3 },
    ambient: { color: '#f0f0ea', intensity: 0.12 },
    sky: { top: '#c6cfd0', horizon: '#eef0e8', bottom: '#e6e8e0', sunGlow: 0.8 },
    fog: { color: '#e3e5dd', density: 0.065 },
    water: { color: '#8eb2ac', opacity: 0.88, roughness: 0.2 },
    toneMapping: 'agx',
    exposure: 1.2,
    post: {
      bloom: { strength: 0.35, radius: 0.9, threshold: 0.85 },
      vignette: { darkness: 0.15, offset: 0.55 },
      saturation: 0.8,
      contrast: 0.92,
      lift: '#8a8a88',
      gamma: '#828280',
      gain: '#807f7c',
      ssao: { enabled: true, radius: 1.5, intensity: 0.8 },
      fxaa: true,
      grain: 0.015,
    },
  },
  {
    id: 'studio-white',
    name: 'Studio White',
    sun: { color: '#ffffff', intensity: 1.8, azimuthDeg: 40, elevationDeg: 60, shadowSoftness: 11, shadowMapSize: 2048 },
    hemi: { sky: '#ffffff', ground: '#ece9e0', intensity: 2.2 },
    ambient: { color: '#ffffff', intensity: 0.35 },
    fill: { color: '#ffffff', intensity: 0.8, position: [-10, 6, 6] },
    sky: { top: '#fbfaf6', horizon: '#f8f7f2', bottom: '#f2f0ea', sunGlow: 0 },
    fog: { color: '#f8f7f2', density: 0.012 },
    water: { color: '#bfe3e4', opacity: 0.7, roughness: 0.3 },
    toneMapping: 'neutral',
    exposure: 1.25,
    post: {
      bloom: { strength: 0.08, radius: 0.4, threshold: 1.6 },
      vignette: { darkness: 0, offset: 0.6 },
      saturation: 0.92,
      contrast: 0.96,
      lift: '#868684',
      gamma: '#848484',
      gain: '#828282',
      ssao: { enabled: true, radius: 1.6, intensity: 0.9 },
      fxaa: true,
      grain: 0,
    },
  },
  {
    id: 'toon-flat',
    name: 'Toon Flat',
    sun: { color: '#fff4dc', intensity: 3.0, azimuthDeg: 60, elevationDeg: 45, shadowSoftness: 0, shadowMapSize: 2048 },
    hemi: { sky: '#9ad0ff', ground: '#6b8f4e', intensity: 0.6 },
    ambient: { color: '#ffffff', intensity: 0.3 },
    fill: { color: '#ffffff', intensity: 3.2, position: [-8, 5, -12] },
    sky: { top: '#45a1f5', horizon: '#a8e1ff', bottom: '#c9f0ff', sunGlow: 0.3 },
    fog: { color: '#bde6ff', density: 0.006 },
    water: { color: '#2cc0d0', opacity: 0.85, roughness: 0.4 },
    toneMapping: 'neutral',
    exposure: 1.0,
    post: {
      bloom: { strength: 0.1, radius: 0.3, threshold: 1.4 },
      vignette: { darkness: 0, offset: 0.6 },
      saturation: 1.35,
      contrast: 1.25,
      lift: N,
      gamma: N,
      gain: N,
      ssao: { enabled: false, radius: 1.0, intensity: 1.0 },
      fxaa: true,
      grain: 0,
      posterize: 5,
    },
  },
  {
    id: 'teal-orange',
    name: 'Cinematic Teal & Orange',
    sun: { color: '#ffae6c', intensity: 3.3, azimuthDeg: 230, elevationDeg: 20, shadowSoftness: 2, shadowMapSize: 4096 },
    hemi: { sky: '#3f8fa0', ground: '#4a3020', intensity: 0.8 },
    ambient: { color: '#2a6f80', intensity: 0.05 },
    fill: { color: '#2ec4d8', intensity: 0.55, position: [-8, 5, -6] },
    sky: { top: '#1a4e6a', horizon: '#f2ae78', bottom: '#e28e58', sunGlow: 1.2 },
    fog: { color: '#6a99a0', density: 0.01 },
    water: { color: '#127e8a', opacity: 0.85, roughness: 0.08 },
    toneMapping: 'aces',
    exposure: 1.1,
    post: {
      bloom: { strength: 0.3, radius: 0.6, threshold: 1.0 },
      vignette: { darkness: 0.55, offset: 0.4 },
      saturation: 1.15,
      contrast: 1.15,
      lift: '#6f8590',
      gamma: '#80807c',
      gain: '#928070',
      ssao: { enabled: true, radius: 1.2, intensity: 1.0 },
      fxaa: true,
      grain: 0.03,
    },
  },
  {
    id: 'candle-lantern',
    name: 'Candle & Lantern Night',
    sun: { color: '#4a5a8a', intensity: 0.25, azimuthDeg: 120, elevationDeg: 30, shadowSoftness: 4, shadowMapSize: 2048 },
    hemi: { sky: '#121a30', ground: '#0a0806', intensity: 0.35 },
    ambient: { color: '#1a1420', intensity: 0.04 },
    extraLights: [
      { type: 'point', color: '#ffa24a', intensity: 16, anchor: 'lantern', offset: [0, 0, 0], distance: 10 },
      { type: 'point', color: '#ff7a2a', intensity: 24, anchor: 'campfire', offset: [0, 0, 0], distance: 11 },
      { type: 'point', color: '#ffb45c', intensity: 11, anchor: 'torch', offset: [0, 0, 0], distance: 8 },
      { type: 'point', color: '#ffc27a', intensity: 4, anchor: 'barrel', offset: [0, 0, 0], distance: 4 },
    ],
    sky: { top: '#05070f', horizon: '#1a1830', bottom: '#0a0a14', sunGlow: 0.2 },
    fog: { color: '#120f18', density: 0.025 },
    water: { color: '#0a1220', opacity: 0.92, roughness: 0.06 },
    toneMapping: 'aces',
    exposure: 1.45,
    post: {
      bloom: { strength: 0.8, radius: 0.6, threshold: 0.6 },
      vignette: { darkness: 0.6, offset: 0.35 },
      saturation: 1.05,
      contrast: 1.08,
      lift: '#807c84',
      gamma: '#82807c',
      gain: '#8c8278',
      ssao: { enabled: true, radius: 1.0, intensity: 1.0 },
      fxaa: true,
      grain: 0.03,
    },
  },
  {
    id: 'product-shot',
    name: 'Clean Product Shot',
    sun: { color: '#ffffff', intensity: 2.4, azimuthDeg: 20, elevationDeg: 50, shadowSoftness: 4, shadowMapSize: 4096 },
    hemi: { sky: '#f4f6ff', ground: '#d0cec8', intensity: 1.2 },
    ambient: { color: '#ffffff', intensity: 0.1 },
    fill: { color: '#e6efff', intensity: 1.0, position: [-10, 4, 2] },
    extraLights: [{ type: 'spot', color: '#fff8f0', intensity: 45, anchor: 'focus', offset: [3, 5, 4], distance: 18 }],
    sky: { top: '#d8dce2', horizon: '#eceef0', bottom: '#f4f4f4', sunGlow: 0.1 },
    fog: { color: '#e8eaec', density: 0.02 },
    water: { color: '#9cc6cc', opacity: 0.8, roughness: 0.15 },
    toneMapping: 'neutral',
    exposure: 1.1,
    post: {
      bloom: { strength: 0.1, radius: 0.4, threshold: 1.4 },
      vignette: { darkness: 0.35, offset: 0.5 },
      saturation: 1.02,
      contrast: 1.06,
      lift: N,
      gamma: N,
      gain: N,
      ssao: { enabled: true, radius: 0.9, intensity: 1.1 },
      fxaa: true,
      grain: 0,
    },
  },
  {
    id: 'kodachrome',
    name: "Kodachrome '72",
    sun: { color: '#ffe2b0', intensity: 3.0, azimuthDeg: 150, elevationDeg: 40, shadowSoftness: 2, shadowMapSize: 2048 },
    hemi: { sky: '#8cc4e8', ground: '#b89a6a', intensity: 0.9 },
    ambient: { color: '#fff0d8', intensity: 0.06 },
    sky: { top: '#3a86c8', horizon: '#d8ecf0', bottom: '#e8e0c8', sunGlow: 0.6 },
    fog: { color: '#d6dcd0', density: 0.008 },
    water: { color: '#1e8c9e', opacity: 0.82, roughness: 0.1 },
    toneMapping: 'reinhard',
    exposure: 1.55,
    post: {
      bloom: { strength: 0.2, radius: 0.5, threshold: 1.1 },
      vignette: { darkness: 0.5, offset: 0.4 },
      saturation: 1.18,
      contrast: 1.12,
      lift: '#8a8478',
      gamma: '#828078',
      gain: '#887f74',
      ssao: { enabled: true, radius: 1.0, intensity: 1.0 },
      fxaa: true,
      grain: 0.06,
    },
  },
  {
    id: 'aurora',
    name: 'Midnight Aurora',
    sun: { color: '#7dffc8', intensity: 0.65, azimuthDeg: 0, elevationDeg: 35, shadowSoftness: 5, shadowMapSize: 2048 },
    hemi: { sky: '#1c5a5a', ground: '#0a1018', intensity: 0.6 },
    ambient: { color: '#204a5a', intensity: 0.05 },
    fill: { color: '#b07dff', intensity: 0.55, position: [-6, 8, -10] },
    sky: { top: '#071a2a', horizon: '#1fd6a0', bottom: '#0a1a28', sunGlow: 0.6 },
    fog: { color: '#0e2a33', density: 0.016 },
    water: { color: '#0b2a33', opacity: 0.9, roughness: 0.05 },
    toneMapping: 'agx',
    exposure: 1.55,
    post: {
      bloom: { strength: 0.7, radius: 0.8, threshold: 0.55 },
      vignette: { darkness: 0.5, offset: 0.4 },
      saturation: 1.15,
      contrast: 1.05,
      lift: '#7c8284',
      gamma: '#7e8484',
      gain: '#7e8888',
      ssao: { enabled: true, radius: 1.0, intensity: 0.9 },
      fxaa: true,
      grain: 0.025,
    },
  },
];

/** How cloudy each ready-made sky is (anything not listed: a few fair-weather clouds). */
const CLOUDS: Readonly<Record<string, number>> = {
  'noon-clear': 0.28, 'golden-hour': 0.4, 'sunset-blaze': 0.5, 'tropical-dawn': 0.35, overcast: 0.88, 'storm-front': 0.95, 'blue-hour': 0.3, 'moonlit-night': 0.22,
  'volcanic-ash': 0.75, 'neon-dusk': 0.25, 'foggy-morning': 0.7, 'studio-white': 0, 'toon-flat': 0.35, 'teal-orange': 0.35, 'candle-lantern': 0.1, 'product-shot': 0,
  kodachrome: 0.4, aurora: 0.1,
};
const withClouds = (r: unknown): unknown => {
  if (!r || typeof r !== 'object') return r;
  const o = r as { id?: string; sky?: Record<string, unknown> };
  return o.sky && o.sky['clouds'] === undefined ? { ...o, sky: { ...o.sky, clouds: CLOUDS[o.id ?? ''] ?? 0.3 } } : o;
};
export const SETUPS: readonly LightSetup[] = RAW.map((r) => normalizeSetup(withClouds(r)));
export const SETUP_IDS: readonly string[] = SETUPS.map((s) => s.id);
/** Ids that older maps stored for looks that have since been renamed. */
export const LEGACY_SETUP_IDS: Readonly<Record<string, string>> = { 'overcast-day': 'overcast' };
/** A library setup by id, also understanding old ids (noon-clear when the id is unknown). */
export const setupById = (id: string): LightSetup => {
  const want = LEGACY_SETUP_IDS[id] ?? id;
  return SETUPS.find((s) => s.id === want) ?? SETUPS[0]!;
};
