import type { Ticket } from './types';

export const TICKETS: Ticket[] = [
  {
    id: 'T0',
    title: 'First-person spike + eye-level audit (go/no-go)',
    reqs: ['R1'],
    decisions: ['D1', 'D2'],
    goal:
      'Before committing to T1–T7, find out whether a world dressed for a chase camera 430 up and 950 back holds up at eye level, about 55 above the road. Ship a flag-gated camera plus a headless audit, and let the human decide.',
    dependsOn: ['nothing (runs first, about half a day)'],
    create: ['src/game/first-person.ts (IF-FP only)', 'scripts/eye-level-audit.mjs', 'src/game/eye-level-audit.ts (pure)', 'tests/eye-level-audit.test.ts', 'docs/FP_SPIKE.md'],
    modify: ["src/game/renderer-3d.ts (branch behind URL flag ?fp=1 inside `if (!freeFly.active)`; no CameraMode change yet)"],
    interfaces: ['IF-FP'],
    behaviour: [
      '?fp=1 places the camera with firstPersonFrame() using the plain track frame (no gyro yet) and FOV 74, near 4, far 60000.',
      'eyeLevelAudit walks the spline every 200 s-units and reports: thin billboards (non-cameraFacing planes with |n·v| < 0.2 within 3000u), terrain edge exposure (half-extent < far·tan(hfov/2)), and decals within 400u of the eye path.',
      'The audit also runs on the builder’s saved props (read-only), so the user’s own props are included.',
      'Output: docs/FP_SPIKE.md with counts per stage, the worst 20 offenders, and a preview URL. The human records go, go-with-dressing or no-go.',
    ],
    acceptance: [
      'AC-1 ?fp=1 is off by default; nothing changes without the flag (physics-parity and all 451 tests green).',
      'AC-2 The audit is deterministic (same report twice) and runs in under 10 s headless.',
      'AC-3 firstPersonFrame passes the T3 AC-1..AC-3 math tests already (straight, loop sweep, fuzz).',
      'AC-4 docs/FP_SPIKE.md exists with the human’s decision recorded before T3 starts.',
    ],
    tests: [{ suite: 'tests/eye-level-audit.test.ts', names: ['thin billboard detection', 'edge exposure detection', 'deterministic report'] }],
    verify: ['npm run check', 'node scripts/eye-level-audit.mjs --course ridge', 'npx vite --config vite.preview.config.ts --host 0.0.0.0 --port 5173  # open with ?fp=1'],
    outOfScope: ['Cockpit art', 'Gyro frame', 'Fixing anything the audit finds (that becomes a T3 sub-ticket)'],
    unverifiable: ['The actual eye-level look; that is the point of the human go/no-go'],
  },
  {
    id: 'T1',
    title: 'Starting zone, goblin push, slingshot retired',
    reqs: ['R7', 'R8'],
    decisions: ['D5', 'D6'],
    goal:
      'A normal run starts on a raised start pad. A starter goblin pushes every racer at once (a real, seeded, tick-driven impulse), and the field rolls downhill into the first loop at engagement speed. The slingshot stays in the code but is no longer reachable from input.',
    dependsOn: ['Retrieval RQ-1, RQ-2, RQ-5 answered'],
    create: ['src/game/sim/start-push.ts', 'tests/start-push.test.ts', 'tests/start-zone.test.ts'],
    modify: [
      "src/game/types.ts (GameStatus += 'pushing'; startMode in engine config)",
      'src/game/scene.ts (elevation table x ∈ [START_X, 1370]: pad + descent; courseY(1370) stays 478)',
      'src/game/track-layout.ts (filter obstacles with x < gate.x after generation, with no RNG skip)',
      'src/game/engine.ts (start(), pushing branch in stepRace, sling input routing gated)',
      "src/game/contracts/commands.ts + core.ts (CONTRACTS_VERSION 2, 'start'/'ready', 'sling_disabled')",
      'src/screens/RaceScreen.tsx (Enter/Space → start; aim hint → "Starter goblin is ready — press Space")',
      "src/game/audio.ts (cue 'push')",
      'scripts/check.mjs, docs/CONTRACTS.md',
    ],
    interfaces: ['IF-START'],
    behaviour: [
      "Status 'ready': racers are on the pad in grid rows (createRacers unchanged), and the loading cover works as before.",
      "The player issues `start` (Enter, Space or the on-screen button). validateCommand refuses it outside 'ready' with a typed reason.",
      "tick 0 of the push: status → 'pushing'. Every racer gets target_i = startPushVelocity(pace, seed, id), and launchOrigin is recorded.",
      "Ticks 1..48: applyPushTick sets vx = target·k/48, vy = 0, z locked, grounded = true. Obstacles are not scanned (the pad is empty).",
      "Tick 48: status → 'flying'. Normal stepRacer continues and gravity on the descent does the rest.",
      "Elevation: the pad is flat at y = 478 − START_DROP for x ∈ [190, 430]. Smoothstep descent over [430, 1060]. Flat run-in over [1060, 1370] at y = 478. The Hands choose START_DROP ∈ [220, 420] as the smallest value meeting AC-3 plus 10%, and record it as a constant.",
      'Layout: obstacles with 190 ≤ x < 1184.44 are removed after generation, so every later obstacle is byte-identical.',
      "startMode 'sling' restores the old routing exactly (used by the regression test).",
    ],
    acceptance: [
      "AC-1 startPushVelocity is deterministic: same (pace, seed, id) → same value. Across 1000 ids every result lies within PUSH_BASE_VX·pace·[0.98, 1.02].",
      'AC-2 pushRampVx(target, 48) === target; k = 0 or k = 49 → ContractError("push_tick_range").',
      'AC-3 Headless race with every roster loadout: every racer crosses x = 1184.44 within 600 ticks of push tick 0 with 700 ≤ vx ≤ 1100, and engages loopRide on the first loop.',
      'AC-4 No racer has vx < 60 for more than 12 consecutive ticks between push end and the gate (no stall on the flat run-in).',
      'AC-5 The layout fingerprint for obstacles with x ≥ 1184.44 equals the pre-change fingerprint on all 3 courses.',
      'AC-6 distance = (x − START_X)/2, TRACK_DISTANCE = 36000 and FINISH = 72190 are unchanged (asserted).',
      "AC-7 In push mode, 'aim'/'launch' commands → { ok:false, reason:'sling_disabled' }; CONTRACTS_VERSION === 2.",
      "AC-8 physics-parity passes when run with startMode 'sling' and the legacy layout flag.",
    ],
    tests: [
      { suite: 'tests/start-push.test.ts', names: ['push velocity is seeded and bounded', 'ramp reaches target on tick 48', 'ramp refuses out-of-range ticks', 'push never touches z or targetLane'] },
      { suite: 'tests/start-zone.test.ts', names: ['every loadout reaches the first loop at engagement speed', 'no stall on the run-in', 'post-gate layout fingerprint unchanged (ridge, canyon, stadium)', 'distance semantics preserved'] },
      { suite: 'tests/contracts.test.ts (update, register in check.mjs)', names: ['CONTRACTS_VERSION is 2', 'start/ready commands gated by status', 'sling commands refused in push mode'] },
    ],
    verify: ['npm run check', 'npm run build', 'node --import tsx --test tests/start-push.test.ts tests/start-zone.test.ts'],
    outOfScope: ['Skill-timed push (Q6)', 'Starter goblin art (T4 renders the pusher sprite)', 'Removing sling code'],
    unverifiable: ['How the descent reads visually from the cockpit (preview URL)'],
  },
  {
    id: 'T2',
    title: 'First-loop merge: gate, pool, ready-up, ordered ghost release',
    reqs: ['R9', 'R10', 'R11'],
    decisions: ['D7', 'D8', 'D9'],
    goal:
      "When a rider crosses the first-loop gate they are held (frozen, intangible, gliding to a slot). Riders ready up, a tick countdown runs, then they are released one at a time in entry-time order at a common speed. They ride the loop and leave as ghosts, then contact racing resumes. The legacy checkpoint is deleted.",
    dependsOn: ['T1'],
    create: ['src/game/merge/pool.ts', 'tests/merge-pool.test.ts', 'tests/merge-race.test.ts', 'src/staging-overlay.css'],
    modify: [
      'src/game/engine.ts (delete legacy checkpoint; gate crossing via qualifying/gate.ts; drive MergePool from stepRace; resolveBumps skips held/ghost; cooldowns → Float64Array(n·n))',
      'src/game/racers.ts (mergeHeld, mergeGhost, loopExitTime fields)',
      'src/game/sim/racer-physics.ts (held branch: no integration except lateral slot glide with the existing PD spring, response 20, damping 6.2)',
      'src/components/StagingOverlay.tsx (reuse for the pool: entry list, READY button, countdown label from pool.countdownLabel)',
      "src/screens/RaceScreen.tsx (mount overlay while status ∈ {'checkpoint','countdown'}; Space/Enter → ready)",
      "src/game/types.ts (snapshot.merge?: { phase, entries, countdownLabel, playerReady })",
      'scripts/check.mjs, docs/MERGE.md (new contract doc)',
    ],
    interfaces: ['IF-MERGE'],
    behaviour: [
      'The gate comes from qualifying/gate.ts for the running course (explicit course argument, law 7). On ridge, gate.x = 1184.44.',
      'Each tick, a rider whose segment crosses the gate plane (the forward-motion and altitude checks from gate.ts apply) calls pool.enter(id, tick, fraction, crossX). The rider becomes mergeHeld: vx = vy = vz = 0, x = crossX, and it glides to slotZ.',
      "The first entry moves status to 'checkpoint' (pool phase). raceTime stops advancing for the whole field while the phase is open, closed or countdown.",
      'Bots ready at entryTick + 90 + 30·rank. The player readies with the `ready` command, or automatically at entryTick + 1800 (flagged autoReady).',
      'The pool closes when every non-finished racer is held, or 1200 ticks after the first entry. Riders still on the run-up become late: they are held on arrival and appended.',
      "Closed and all held riders ready → status 'countdown' for 360 ticks (labels 3/2/1/GO!), derived from staging/lifecycle ticks. Pause freezes it.",
      "On GO: release index k is scheduled at GO + 42·k. It is gated on occupancy (the previous released rider's loopRide progress ≥ 0.25 or exited). Otherwise retry every 6 ticks, and after 8 retries release with the flag forced.",
      'Release: mergeHeld = false, vx = 700, vy = vz = 0, mergeGhost = true. The rider rides into the loop through the normal loop-engagement code.',
      'mergeGhost clears 0.75 s after the loop exit. resolveBumps runs again (R11), and the shove still clamps to 0..3 until T6.',
      "After the last release the pool is 'done' and snapshot.merge is removed.",
    ],
    acceptance: [
      'AC-1 mergeOrder sorts by entryTime, then racerId. Property test with 500 random entry sets.',
      'AC-2 Headless 4-racer race on each course: the order in which riders exit the first loop equals ascending entryTime (100 seeds).',
      'AC-3 No resolveBumps contact involves a held or ghost rider (instrumented counter = 0). Contacts are possible within 1 tick after the ghost tail clears.',
      'AC-4 Minimum spacing between consecutive released riders at loop exit ≥ 200 x-units (100 seeds).',
      'AC-5 A rider that never readies (player idle) is released with the autoReady flag, never dropped. A rider stuck behind (stalled bot) is late, never dropped.',
      'AC-6 grep finds no setInterval or setTimeout in src/game/engine.ts. checkpointX, triggerCheckpoint and releaseFromCheckpoint are gone.',
      'AC-7 No racer x changes by more than |vx|·dt + 1e-9 on any tick (no teleport), checked over whole runs.',
      'AC-8 Two runs with the same seed give identical fingerprints: entry ticks, release ticks, flags.',
      'AC-9 Pausing for N ticks during the countdown shifts every release tick by exactly N.',
    ],
    tests: [
      { suite: 'tests/merge-pool.test.ts', names: ['order is entry time then id', 'bots ready by rank', 'pool closes on all-held or timeout', 'player auto-ready flagged', 'late rider appended and flagged', 'occupancy delays and forced flag', 'countdown labels are tick-derived', 'refusals: duplicate entry, ready when not held', 'pause shifts schedule'] },
      { suite: 'tests/merge-race.test.ts', names: ['exit order equals entry order (100 seeds × 3 courses)', 'no contacts while held or ghost', 'contacts resume after ghost tail', 'no teleport', 'deterministic fingerprint'] },
    ],
    verify: ['npm run check', 'npm run build', 'node --import tsx --test tests/merge-pool.test.ts tests/merge-race.test.ts', "grep -nE 'setInterval|setTimeout' src/game/engine.ts  # expect no output"],
    outOfScope: ['Fields > 4: T2 refuses with merge_field_unsupported and runs without a merge (backlog)', 'Qualifying heats before the race', 'Leaderboard orbit visuals'],
    unverifiable: ['How the held riders look beside the loop mouth (preview URL)'],
  },
  {
    id: 'T3',
    title: 'First-person rig, tank-window aperture, gyro ball',
    reqs: ['R1', 'R5'],
    decisions: ['D1', 'D2', 'D3', 'D4'],
    goal:
      'The race is seen from the goblin’s eye inside the gyro frame, through the armoured window aperture. Each ball is a rolling core between two level brass caps, driven by sim-owned roll phase.',
    dependsOn: ['T2 (the camera must survive the hold and the loop)'],
    create: ['src/game/first-person.ts', 'src/game/gyro-ball.ts', 'src/components/CockpitWindow.tsx', 'src/cockpit.css', 'tests/first-person.test.ts', 'tests/gyro-ball.test.ts', 'tests/cockpit-window.mjs'],
    modify: [
      "src/game/types.ts (CameraMode += 'first_person', default)",
      'src/game/preferences.ts (degrade unknown, one-time cockpitDefaultApplied migration)',
      "src/game/renderer-3d.ts (first_person branch inside `if (!freeFly.active)`; racer mesh = group{core, capL, capR}; the spin line is replaced by the gyroPose quaternions; own mesh hidden in FP; setViewOffset from cockpitLayout)",
      'src/game/racers.ts + sim/racer-physics.ts (rollPhase, rollRate via advanceRoll)',
      'src/components/SettingsPanel.tsx (camera option)',
      'tests/racer-pool.test.ts (mesh tree: 3 children, shared geometry refcounts)',
    ],
    interfaces: ['IF-FP', 'IF-GYRO', 'IF-COCKPIT (cockpitLayout only)'],
    behaviour: [
      'Per render: gyroFrameFor(sample, loop, centre, falling, lastGrounded) → gyroPose(interpolated rollPhase) → firstPersonFrame(...). Renderer3D copies position, up and lookAt(position + forward) and sets fov/near/far only when they change.',
      'Loop: the gyro up points at the loop centre, so the view goes head-over-heels with the track (the real feel of a loop), and up never degenerates.',
      'Fall: the frame freezes at the last grounded frame and forward follows the world velocity (slerp 4/s).',
      'The window: the canvas stays full-screen behind; CockpitWindow draws the bezel PNG (placeholder CSS gradient until T4 art) with a mask derived from cockpitLayout.',
      "Third-person modes are untouched. Switching modes via setOptions takes effect on the next frame without reallocating.",
    ],
    acceptance: [
      'AC-1 Straight grounded descent: position = centre + up·24 + forward·6 (±1e-6); forward·up = 0 (±1e-6).',
      'AC-2 Loop sweep, 360 samples of angle: up is always unit length, finite, and |forward·up| ≤ 0.985 or degenerate = true with a valid output.',
      'AC-3 Canyon bank and ramp samples: output orthonormal; no NaN over 10 000 fuzzed inputs.',
      'AC-4 advanceRoll: grounded rollPhase delta = hypot(vx,vz)·dt/31; airborne rollRate decays by exp(−0.6·dt); phase wraps within [0, TAU).',
      'AC-5 gyroPose: rotating the gyro quaternion leaves world-up unchanged for any rollPhase (caps and goblin level). Core rotation about frame.right = −rollPhase.',
      'AC-6 Mesh tree: every racer = 1 core + 2 caps. Only 3 geometries exist regardless of field size. No new Geometry, Material or Quaternion inside render() (allocation spy).',
      'AC-7 cockpitLayout(1920,1080) and (3840,2160): aperture inside the viewport, horizonY = aperture centre; DOM mask matches ±1 px in headless Chromium.',
      "AC-8 A stored cameraMode 'banana' → 'first_person' with no throw.",
      'AC-9 physics-parity unchanged (rollPhase excluded from the fingerprint).',
    ],
    tests: [
      { suite: 'tests/first-person.test.ts', names: ['straight descent eye placement', 'loop sweep never degenerates', 'fuzz: finite orthonormal output', 'fall freezes frame'] },
      { suite: 'tests/gyro-ball.test.ts', names: ['roll phase grounded law', 'air decay', 'caps stay level for all phases', 'core rolls about right axis'] },
      { suite: 'tests/cockpit-window.mjs (headless DOM)', names: ['aperture geometry 1920×1080', 'aperture geometry 3840×2160', 'reduced motion disables bob'] },
    ],
    verify: ['npm run check', 'npm run build', 'node tests/cockpit-window.mjs', 'npx vite --config vite.preview.config.ts --host 0.0.0.0 --port 5173  # human checks the view'],
    outOfScope: ['Cockpit art (T4)', 'Head-bob tuning beyond 6 px', 'VR'],
    unverifiable: ['Rendered FP frame, motion sickness, depth precision at near = 4 (preview URL)'],
  },
  {
    id: 'T4',
    title: 'PNG cockpit HUD: working gauges, steampunk yoke, goblin arms',
    reqs: ['R2', 'R3', 'R4'],
    decisions: ['D3', 'D14'],
    goal:
      'Painted bezel and gauge clusters with SVG needles bound to live state. A yoke that rotates with steering. Goblin arms pinned to the yoke grips, their shoulders cropped below the screen edge.',
    dependsOn: ['T3', 'Q8 art approval'],
    create: ['src/game/cockpit.ts', 'src/components/CockpitHud.tsx', 'src/components/cockpit/{Yoke,Arms,Gauge}.tsx', 'public/art/cockpit/* (9 images)', 'tests/cockpit.test.ts', 'tests/cockpit-hud.mjs'],
    modify: [
      'src/game/engine.ts (getCockpitState(): fills one reused CockpitState at render time)',
      'src/screens/RaceScreen.tsx (FP mode: mount CockpitHud, hide .hud-telemetry; gear, pause and restart stay reachable)',
      'src/game/assets preloader (cockpit images decoded before the race, law 4)',
      'src/cockpit.css (overflow:hidden root, reduced-motion and high-contrast variants)',
    ],
    interfaces: ['IF-COCKPIT'],
    behaviour: [
      'A requestAnimationFrame loop inside CockpitHud reads engine.getCockpitState() and writes CSS transforms through refs. No React re-render per frame. Gauges with slow-changing values (position, time) still use the snapshot.',
      'steer = clamp(−vz/(650·handling), −1, 1); yoke rotation = steer·38°. It uses the same vz the physics integrates, so the yoke leads the lane change.',
      'Arms: armPose() rotates each arm image about its shoulder (below the viewport) to reach the grip, whose position is rotated with the yoke. The left arm is the mirrored image.',
      'Gauges: speed dial 0–360 km/h over 240°; boost pressure = charges/max; bounce lamps; shield meter 0–12 s; inclinometer ±30% grade; race-time nixie; the position medallion is reused. Every gauge has role="meter" and aria-valuenow.',
      "Pool and countdown phases: the centre gauge shows the countdownLabel. During 'pushing' the starter-goblin sprite plays at the bottom-left of the aperture.",
    ],
    acceptance: [
      'AC-1 needleAngle(min) = −sweep/2 and needleAngle(max) = +sweep/2; values are clamped outside the range.',
      'AC-2 yokeAngleDeg(steerFrom(±650·h, h)) = ∓38; steerFrom(0) = 0.',
      'AC-3 armPose: the hand stays within 2 px of its grip across yoke −38..38°; the shoulder y is greater than the viewport height at 1280×720, 1920×1080 and 3840×2160 (arms leave through the bottom edge).',
      'AC-4 Headless DOM: the cockpit root has overflow:hidden; the yoke transform changes after a synthetic steer; gauges expose aria values that match the injected CockpitState.',
      'AC-5 No image decode during the race: all 9 images are present in the preload manifest; the network log after the race starts has no cockpit requests.',
      'AC-6 Reduced motion: no CSS transitions on needles and bob = 0. High contrast: gauge readouts shown as text.',
      'AC-7 Bundle gzip delta ≤ 40 kB (PNGs live in public/, not in the bundle).',
    ],
    tests: [
      { suite: 'tests/cockpit.test.ts', names: ['needle mapping', 'steer and yoke law', 'arm reaches grip', 'shoulders below viewport', 'layout at 3 viewports'] },
      { suite: 'tests/cockpit-hud.mjs (headless DOM, mock engine)', names: ['root clips arms', 'yoke follows steer', 'aria meters', 'reduced motion'] },
    ],
    verify: ['npm run check', 'npm run build', 'node tests/cockpit-hud.mjs'],
    art: ['Images 1–9 from D14. Image 10 is reserved for T5.'],
    outOfScope: ['Touch/drag yoke input', 'Animated cockpit damage states'],
    unverifiable: ['How well the art fits the world (human review)'],
  },
  {
    id: 'T5',
    title: 'Effect runtime: explosions, collisions, dust, smoke, sparks',
    reqs: ['R6'],
    decisions: ['D10', 'D14'],
    goal:
      'The effects the engine already emits become visible. Typed effect events go through a fixed billboard pool and one Points object, preloaded, bounded, culled and reduced-motion aware.',
    dependsOn: ['T3'],
    create: ['src/game/effects/events.ts', 'src/game/effects/pool.ts', 'src/game/effects/specs.ts', 'src/game/effects/renderer-fx.ts', 'tests/effects.test.ts'],
    modify: [
      'src/game/sim/context.ts (SimFx.effect(kind, x, y, z, scale, racerId))',
      'src/game/engine.ts (the ~25 emit() sites also push an EffectEvent, mapping below; frame.effects cursor view)',
      'src/game/scene.ts (SceneFrame.effects: EffectQueue read-only view)',
      'src/game/renderer-3d.ts (update + draw hook; frame.particles drawn as Points)',
      'preloader (anim-43, anim-46, the regenerated anim-44, procedural puff baked once)',
    ],
    interfaces: ['IF-FX'],
    behaviour: [
      'Mapping: tnt, cauldron and lava plunge → explosion + smoke. Heavy bump → impact + sparks. Light bump, shove and shield absorb → sparks. Landing, hop, recover and ground impact → dust. Boost → smoke (small). Loop exit → sparks. Finish → no new effect (existing fireworks are out of scope).',
      'Specs: explosion anim-43 480u 16fps life 0.25 s; impact anim-44 (regenerated) 220u 14fps 0.29 s, fallback anim-43 at 160u; dust puff 60→180u life 0.6 s ×3; smoke puff dark 90→260u life 1.1 s rise 40u/s ×2; sparks Points ≤ 160.',
      'The renderer reads events newer than its cursor, maps engine → world via placementFromEngine, culls beyond 6000u, and spawns into the pool. When the pool is full the effect is dropped and counted (never allocated).',
      'Reduced motion: sheets hold frame 1 at 0.5 opacity for half their life; puffs don’t scale; sparks are skipped.',
    ],
    acceptance: [
      'AC-1 EffectQueue: 10 000 pushes allocate 0 objects after construction (heap snapshot delta); overflow counter is correct.',
      'AC-2 BillboardPool never exceeds 64 live; dropped counts the refusals; despawn happens at exactly spawn + life.',
      'AC-3 Sheet frame index at t = floor((t − t0)·fps) mod 4; frame 1 held under reduced motion.',
      'AC-4 An unknown kind throws ContractError("unknown_effect_kind").',
      'AC-5 Headless race: every mapped gameplay event produces exactly one EffectEvent of the mapped kind (instrumented).',
      'AC-6 renderer-fx render() allocates nothing (spy) and data-render-cpu-ms stays within 1 ms of baseline in the integration benchmark.',
    ],
    tests: [{ suite: 'tests/effects.test.ts', names: ['queue ring & overflow', 'pool bound & drop count', 'frame timing', 'reduced motion', 'unknown kind refused', 'event mapping coverage'] }],
    verify: ['npm run check', 'npm run build', 'node --import tsx --test tests/effects.test.ts tests/integration-benchmarks.test.ts'],
    art: ['Image 10: regenerate anim-44 spark burst, then run scripts/analyze-animated-sheets.mjs (centroid drift < 20 px, element delta > 0.15, magenta < 0.2%)'],
    outOfScope: ['Regenerating anim-45/47/48/49/51/52', 'Gore on collisions (tone)', 'Screen shake in FP'],
    unverifiable: ['How the effects look in-world (preview URL)'],
  },
  {
    id: 'T6',
    title: 'Lane network: model, validation, runtime steering, storage',
    reqs: ['R12', 'R13'],
    decisions: ['D11', 'D12', 'D13'],
    goal:
      'Authored lane paths with merge, split and OOB nodes drive steering, shove, CPU aim and recovery when a network exists for the course. Behaviour is bit-identical when none does.',
    dependsOn: ['T2 (the shove clamp is generalised here)', 'Retrieval RQ-3, RQ-4'],
    create: ['src/game/lane-network.ts', 'src/game/lane-storage.ts', 'tests/lane-network.test.ts', 'tests/lane-storage.test.ts', 'tests/lane-parity.test.ts', 'docs/LANE_NETWORK.md'],
    modify: [
      'src/game/sim/racer-physics.ts (steering target and clamp from resolveLaneTarget; OOB check → recoverRacer(\'oob\'))',
      'src/game/sim/context.ts (RecoveryPolicy handles the \'oob\' reason)',
      'src/game/sim/cpu-driver.ts (candidate targets = adjacentPath centres when a network exists)',
      'src/game/engine.ts (changeLane → adjacentPath; shove → adjacentPath in the shove direction or stay; network loaded per course)',
      'src/game/racers.ts (pathId)',
      'vite.config.ts (POST /api/backup-lane-paths)',
    ],
    interfaces: ['IF-LANES', 'IF-LANESTORE'],
    behaviour: [
      'Sampling: linear interpolation in x between consecutive nodes of the path; x outside the path → null.',
      'Racer path changes: input ±1 → adjacentPath at the current x (nearest centre in that direction whose corridor exists at x). At a path end: a merge node → the single outgoing path; a split node → the outgoing path chosen by input bias, else nearest z; an oob node → OOB.',
      'Corridor: the union of [z − halfWidth, z + halfWidth] over paths active at x, intersected with ±(480 − 37). Steering clamps to it instead of the fixed corridor.',
      'The PD spring and the steerLockedUntil cut are unchanged: only targetZ, zMin and zMax change.',
      'Recovery picks the nearest gap-free path centre instead of laneZ(candidate).',
    ],
    acceptance: [
      'AC-1 With network null, physics-parity and all 451 prior tests pass unchanged. lane-parity compares 50 seeded full races (legacy vs null-network): identical fingerprints.',
      'AC-2 validateLaneNetwork returns each LaneRefusal code for a crafted document (7 cases) and accepts the sample ridge network.',
      'AC-3 inferKind matches the authored kind on valid networks; mismatches → kind_mismatch.',
      'AC-4 sampleLane is continuous at nodes and within node z bounds on each segment (property test).',
      'AC-5 A scripted racer on a path ending in an OOB node triggers recoverRacer(\'oob\') on the exact crossing tick.',
      'AC-6 Split: bias −1/+1 picks the respective branch. Merge: both inbound paths continue on the same outbound path.',
      'AC-7 Storage: round trip preserves unknown fields; duplicate IDs refused; quotaExceeded reported; a failed write leaves the previous document readable.',
    ],
    tests: [
      { suite: 'tests/lane-network.test.ts', names: ['refusal codes', 'kind inference', 'sampling continuity', 'corridor union', 'adjacent/successor', 'oob crossing'] },
      { suite: 'tests/lane-parity.test.ts', names: ['null network is bit-identical (50 seeds × 3 courses)'] },
      { suite: 'tests/lane-storage.test.ts', names: ['round trip', 'backup restore', 'quota', 'invalid refused keeps last valid'] },
    ],
    verify: ['npm run check', 'npm run build', 'node --import tsx --test tests/lane-network.test.ts tests/lane-parity.test.ts tests/lane-storage.test.ts'],
    outOfScope: ['Re-dressing environment.ts to follow authored lanes', 'Curved (spline) segments', 'Right-of-way rules at merges'],
    unverifiable: [],
  },
  {
    id: 'T7',
    title: 'Builder “Lanes & Paths” tool',
    reqs: ['R13', 'R14'],
    decisions: ['D11', 'D13'],
    goal:
      'Inside the existing 3D builder you can author lane networks: drag node handles on the track surface, insert and delete nodes, split, merge, mark OOB, snap to lane centres and a grid, with shared undo. Saving is validated.',
    dependsOn: ['T6'],
    create: ['src/game/lane-path-tool.ts', 'src/components/builder/LanePanel.tsx', 'tests/lane-edit.test.ts', 'tests/lane-panel.mjs'],
    modify: [
      'src/game/track-builder-3d.ts (lane gizmos: one InstancedMesh ≤ 512 nodes coloured by kind; one line BufferGeometry per path rebuilt only on edit; picking; drag via raycastSurface → engine (x, z) inverse mapping)',
      "src/components/TrackBuilderUI.tsx (category 'lanes' in the strip; LanePanel with node inspector, kind buttons, validation list, Save/Export/Import)",
      'undo: entries become { props?, lanes? } so one Ctrl+Z covers both documents',
    ],
    interfaces: ['IF-BUILDER'],
    behaviour: [
      'Keys while the tool is active: N new path (click-click-Enter), I insert on the hovered segment, Del delete node, K cycle kind, S split from the selected node, M merge the selected path end into the next clicked node, O mark the selected path OOB, Ctrl+Z / Ctrl+Y undo and redo.',
      'Drag: pointer → raycastSurface → world → engine x (inverse track-space) and z (laneZFromLateral). Then snapNode (lanes ±30 z, grid 50 x). A move that would break monotone x is refused, and the handle stays put with a toast giving the reason.',
      'The validation list updates on every edit. Save is disabled while errors exist, and clicking an error focuses the offending node.',
      '“Test drive” closes the builder and restarts the race with the edited network loaded.',
    ],
    acceptance: [
      'AC-1 applyLaneEdit never mutates its input (frozen-object test) and refuses illegal edits with a reason (split on an oob node, merge that creates a cycle, non-monotone move).',
      'AC-2 Every edit op followed by undo gives a deep-equal network; redo restores it.',
      'AC-3 snapNode snaps to 360/120/−120/−360 within 30 z and to multiples of 50 in x when enabled.',
      'AC-4 Gizmo rebuild counts: dragging a node for 100 frames rebuilds only its paths’ geometry, 0 new materials (spy).',
      'AC-5 Headless DOM: the lanes category renders, validation errors are listed with aria-live, Save is disabled while invalid, and all controls have labels.',
    ],
    tests: [
      { suite: 'tests/lane-edit.test.ts', names: ['immutability', 'refusals', 'undo/redo round trip', 'snapping'] },
      { suite: 'tests/lane-panel.mjs (headless DOM)', names: ['category and panel render', 'save disabled when invalid', 'a11y labels'] },
    ],
    verify: ['npm run check', 'npm run build', 'node tests/lane-panel.mjs'],
    outOfScope: ['Spline handles/bezier tangents', 'Multi-course network copy', 'Collaborative editing'],
    unverifiable: ['3D gizmo feel and pick accuracy (preview URL)'],
  },
];
