"""Writes apps/web/src/build/icons.ts: explicit lucide imports for every icon the build HUD and the tool presets name (so unused icons stay out of the bundle).
Run it again after adding a tool whose icon is not in the list."""
names = """Activity,AlignCenter,Aperture,ArrowDownToLine,ArrowUpFromLine,AudioLines,Backpack,BarChart3,Blend,Bone,Broom,Brush,Camera,Circle,CircleDot,Clapperboard,Combine,Compass,Copy,CornerRightDown,Crosshair,Droplet,Eraser,Film,Flame,FlipHorizontal,Focus,GitBranch,GitMerge,Globe,Grid3x3,Hand,Hash,HeartPulse,Image,KeyRound,Layers,Link,Magnet,Maximize,Mic,Minimize,Minus,MinusCircle,Monitor,Moon,MousePointer,MousePointer2,Move,Move3d,MoveHorizontal,Network,Orbit,PaintBucket,Paintbrush,Palette,Pen,Pencil,Pipette,PlaneTakeoff,Play,PlusCircle,Radio,Repeat,Rotate3d,RotateCcw,Ruler,Scissors,Shapes,Shield,Shirt,SlidersHorizontal,Sparkles,Stamp,Sun,Target,Timer,Trash2,TrendingUp,Type,Unlink,User,Volume2,VolumeX,Waves,Wind,ZoomIn,Package,TreePalm,Gem,Trophy,Square,Smile,Mountain,Shovel,Plus,Sprout,Flower2,Flag,Eye,EyeOff,Map,Dice5,X,Check,Save,Undo2,Footprints,Users,Settings2""".split(',')
names = sorted(set(names))
out = "// Generated by scripts/gen-build-icons.py: every icon the build HUD and the tool presets name, imported by name so unused icons stay out of the bundle.\n"
out += "import { " + ", ".join(names) + ", type LucideIcon } from 'lucide-react';\n\n"
out += "export const ICONS: Readonly<Record<string, LucideIcon>> = { " + ", ".join(names) + " };\n"
out += "export const iconByName = (name: string): LucideIcon => ICONS[name] ?? Package;\n"
open('E:/AI/hm2-art/harness/repo/apps/web/src/build/icons.ts', 'w', encoding='utf8').write(out)
print(len(names))
