/**
 * Keys generated magenta-background art into transparent, trimmed masters (ART tickets).
 *
 *   node --import tsx scripts/key-art.ts --set avatar-parts [--only id1,id2]
 *   node --import tsx scripts/key-art.ts --set garage-decals
 *   node --import tsx scripts/key-art.ts --set track-sprites
 *
 * Reads the set's raw folder under `art-src/` (raws never ship: see tests/art-budget.test.ts),
 * runs `src/game/meta/chroma-key.ts` (detect key → matte → decontaminate → despill → choke → trim →
 * premultiplied downsample), writes `<out>/<id>.png`, and prints one QA line per file. The
 * avatar-parts set also merges its entries into `src/game/meta/painted-parts.generated.ts` (entries
 * for other ids are kept). Exits 1 when any file fails QA, so a batch agent knows to regenerate.
 *
 * PNG only (pure Node; ImageMagick fallback). Convert a JPEG first:
 *   convert in.jpg -depth 8 art-src/<set>/raw/<id>.png
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { DEFAULT_KEY_PARAMS, keyPart, type Rgba } from '../src/game/meta/chroma-key';
// @ts-expect-error — plain .mjs helper without types
import { decodePng, encodePng } from './edge-magenta-lib.mjs';

interface SetConfig { raw: string; out: string; publicPrefix: string; master: number; manifest?: string }
const SETS: Record<string, SetConfig> = {
  'avatar-parts': { raw: 'art-src/avatar-parts/raw', out: 'public/avatar-parts/keyed', publicPrefix: '/avatar-parts/keyed', master: 512, manifest: 'src/game/meta/painted-parts.generated.ts' },
  'garage-decals': { raw: 'art-src/garage-decals/raw', out: 'public/art/garage/decals', publicPrefix: '/art/garage/decals', master: 256 },
  'track-sprites': { raw: 'art-src/track/raw', out: 'public/art/track-obstacles', publicPrefix: '/art/track-obstacles', master: 512 },
};

const args = process.argv.slice(2);
const setName = args[args.indexOf('--set') + 1];
const config = SETS[setName];
if (!config || args.indexOf('--set') < 0) {
  console.error(`usage: --set ${Object.keys(SETS).join('|')} [--only id,id]`);
  process.exit(2);
}
const only = args.includes('--only') ? new Set(args[args.indexOf('--only') + 1].split(',')) : null;
mkdirSync(config.out, { recursive: true });

const lines = new Map<string, string>();
let failed = 0; let keyed = 0;
for (const file of existsSync(config.raw) ? readdirSync(config.raw).sort() : []) {
  if (!/\.png$/i.test(file)) continue;
  const id = file.replace(/\.png$/i, '');
  if (only && !only.has(id)) continue;
  const { w, h, data } = decodePng(path.join(config.raw, file));
  const img: Rgba = { width: w, height: h, data: new Uint8ClampedArray(data.buffer, data.byteOffset, data.length) };
  const t0 = Date.now();
  const { master, qa } = keyPart(img, DEFAULT_KEY_PARAMS, config.master);
  encodePng(path.join(config.out, `${id}.png`), master.width, master.height, Buffer.from(master.data.buffer, master.data.byteOffset, master.data.length));
  keyed++; if (qa.verdict === 'fail') failed++;
  console.log(`${qa.verdict.toUpperCase().padEnd(4)} ${id.padEnd(36)} ${w}×${h} → ${master.width}×${master.height}  key=${qa.key}  residual=${qa.residualMagenta}  ${Date.now() - t0} ms ${qa.notes.join('; ')}`);
  lines.set(id, `  '${id}': { file: '${config.publicPrefix}/${id}.png', raw: '${config.raw}/${file}', sourceFormat: 'png', width: ${master.width}, height: ${master.height}, qa: ${JSON.stringify({ verdict: qa.verdict, key: qa.key, keyDeviation: qa.keyDeviation, coverage: qa.coverage, residualMagenta: qa.residualMagenta, borderTouch: qa.borderTouch, notes: qa.notes })} },`);
}

if (config.manifest) {
  // Merge: keep every existing entry, replace the ones keyed now.
  const previous = existsSync(config.manifest) ? readFileSync(config.manifest, 'utf8') : '';
  for (const match of previous.matchAll(/^ {2}'([^']+)': \{.*\},$/gm)) if (!lines.has(match[1])) lines.set(match[1], match[0]);
  const body = [...lines.keys()].sort().map((id) => lines.get(id)).join('\n');
  writeFileSync(config.manifest, `// AUTO-GENERATED by scripts/key-art.ts --set ${setName} — do not edit by hand.
export interface KeyedPartFile {
  file: string; raw: string; sourceFormat: 'jpeg' | 'png'; width: number; height: number;
  qa: { verdict: 'pass' | 'warn' | 'fail'; key: number[]; keyDeviation: number; coverage: number; residualMagenta: number; borderTouch: number; notes: string[] };
}
export const KEYED_PARTS: Record<string, KeyedPartFile> = {
${body}
};
`);
}
console.log(`${keyed} keyed now, ${failed} failed QA${config.manifest ? `, ${lines.size} in the manifest` : ''}`);
process.exit(failed ? 1 : 0);
