import { LookPreset } from './types';

export const LOOKS: LookPreset[] = [
  {
    id: 'noon-clear',
    name: 'Noon Clear',
    tags: ['noon', 'clear', 'tropical'],
    doc: 'A blazing mid-day look with clear skies, high sun intensity, and deep blue ocean views.',
    params: {
      skyZenith: '#0a3c80',
      skyHorizon: '#87ceeb',
      skyGround: '#325a2b',
      sunElevation: 62,
      sunAzimuth: 180,
      sunKelvin: 5800,
      sunIntensity: 6.5,
      ambientIntensity: 1.5,
      ambientSky: '#bfd8ff',
      ambientGround: '#405040',
      fogColor: '#c0e0ff',
      fogDensity: 0.002,
      exposure: 1.0,
      bloom: 0.2,
      saturation: 1.1,
      contrast: 1.1,
      vignette: 0.1,
      waterColor: '#006677',
      waterOpacity: 0.6,
      cloudCover: 0.1
    }
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    tags: ['golden', 'sunset', 'warm'],
    doc: 'Warm golden light casting long dramatic shadows across the tropical landscape.',
    params: {
      skyZenith: '#1c305a',
      skyHorizon: '#fd9a33',
      skyGround: '#4c321a',
      sunElevation: 12,
      sunAzimuth: 250,
      sunKelvin: 3600,
      sunIntensity: 5.0,
      ambientIntensity: 1.2,
      ambientSky: '#f7bb8a',
      ambientGround: '#52361d',
      fogColor: '#e69a5a',
      fogDensity: 0.005,
      exposure: 1.1,
      bloom: 0.5,
      saturation: 1.2,
      contrast: 1.1,
      vignette: 0.2,
      waterColor: '#0e606b',
      waterOpacity: 0.7,
      cloudCover: 0.2
    }
  },
  {
    id: 'sunset-blaze',
    name: 'Sunset Blaze',
    tags: ['sunset', 'blaze', 'vibrant'],
    doc: 'An intense blazing sunset with deep purples and fiery orange skies.',
    params: {
      skyZenith: '#3a1c54',
      skyHorizon: '#ff3c1c',
      skyGround: '#201026',
      sunElevation: 2,
      sunAzimuth: 270,
      sunKelvin: 2400,
      sunIntensity: 4.0,
      ambientIntensity: 1.0,
      ambientSky: '#a04080',
      ambientGround: '#281420',
      fogColor: '#7a2a50',
      fogDensity: 0.008,
      exposure: 1.0,
      bloom: 1.2,
      saturation: 1.3,
      contrast: 1.2,
      vignette: 0.3,
      waterColor: '#2a1a4a',
      waterOpacity: 0.8,
      cloudCover: 0.3
    }
  },
  {
    id: 'tropical-dawn',
    name: 'Tropical Dawn',
    tags: ['dawn', 'morning', 'fresh'],
    doc: 'A quiet peach and teal sunrise over the calm morning ocean.',
    params: {
      skyZenith: '#1c4a5c',
      skyHorizon: '#ffaa88',
      skyGround: '#1f2c24',
      sunElevation: 6,
      sunAzimuth: 90,
      sunKelvin: 3200,
      sunIntensity: 3.5,
      ambientIntensity: 1.1,
      ambientSky: '#a0c0cc',
      ambientGround: '#2d3d34',
      fogColor: '#ffd0b0',
      fogDensity: 0.006,
      exposure: 1.0,
      bloom: 0.4,
      saturation: 1.05,
      contrast: 0.95,
      vignette: 0.15,
      waterColor: '#1c5c63',
      waterOpacity: 0.55,
      cloudCover: 0.15
    }
  },
  {
    id: 'overcast-day',
    name: 'Overcast Day',
    tags: ['cloudy', 'grey', 'diffuse'],
    doc: 'A diffuse, grey-toned afternoon with soft lighting and muted colors.',
    params: {
      skyZenith: '#606870',
      skyHorizon: '#8a929a',
      skyGround: '#3d4038',
      sunElevation: 35,
      sunAzimuth: 160,
      sunKelvin: 7000,
      sunIntensity: 1.2,
      ambientIntensity: 2.2,
      ambientSky: '#707880',
      ambientGround: '#3b3e39',
      fogColor: '#8a929a',
      fogDensity: 0.008,
      exposure: 0.9,
      bloom: 0.1,
      saturation: 0.7,
      contrast: 0.8,
      vignette: 0.1,
      waterColor: '#3c4f52',
      waterOpacity: 0.65,
      cloudCover: 0.85
    }
  },
  {
    id: 'storm-front',
    name: 'Storm Front',
    tags: ['storm', 'cloudy', 'dark'],
    doc: 'Violent dark slate skies and deep fog rolling in from the open ocean.',
    params: {
      skyZenith: '#2a2e33',
      skyHorizon: '#3e4442',
      skyGround: '#1c1e1c',
      sunElevation: 25,
      sunAzimuth: 110,
      sunKelvin: 6000,
      sunIntensity: 0.8,
      ambientIntensity: 1.6,
      ambientSky: '#38403d',
      ambientGround: '#1e201e',
      fogColor: '#33403a',
      fogDensity: 0.012,
      exposure: 0.85,
      bloom: 0.3,
      saturation: 0.8,
      contrast: 1.3,
      vignette: 0.35,
      waterColor: '#1d3a3d',
      waterOpacity: 0.9,
      cloudCover: 1.0
    }
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    tags: ['blue', 'twilight', 'quiet'],
    doc: 'A peaceful deep blue twilight just after sunset with a thin magenta horizon.',
    params: {
      skyZenith: '#0c1a3a',
      skyHorizon: '#bf6b8a',
      skyGround: '#0f121c',
      sunElevation: -4,
      sunAzimuth: 285,
      sunKelvin: 12000,
      sunIntensity: 0.1,
      ambientIntensity: 1.8,
      ambientSky: '#203566',
      ambientGround: '#0a0d14',
      fogColor: '#102040',
      fogDensity: 0.003,
      exposure: 1.0,
      bloom: 0.6,
      saturation: 1.15,
      contrast: 1.05,
      vignette: 0.25,
      waterColor: '#0a1c30',
      waterOpacity: 0.75,
      cloudCover: 0.05
    }
  },
  {
    id: 'moonlit-night',
    name: 'Moonlit Night',
    tags: ['night', 'moon', 'dark'],
    doc: 'A cool, starry night illuminated by a brilliant silvery moon.',
    params: {
      skyZenith: '#03060f',
      skyHorizon: '#081024',
      skyGround: '#010205',
      sunElevation: -20,
      sunAzimuth: 330,
      sunKelvin: 9000,
      sunIntensity: 0.25,
      ambientIntensity: 0.4,
      ambientSky: '#0c1224',
      ambientGround: '#020408',
      fogColor: '#050a14',
      fogDensity: 0.002,
      exposure: 1.3,
      bloom: 0.7,
      saturation: 0.75,
      contrast: 1.15,
      vignette: 0.4,
      waterColor: '#020814',
      waterOpacity: 0.85,
      cloudCover: 0.2
    }
  },
  {
    id: 'volcanic-ash',
    name: 'Volcanic Ash',
    tags: ['dust', 'apocalypse', 'glow'],
    doc: 'An eerie volcanic sky choked with ash, casting an ominous red-orange glow.',
    params: {
      skyZenith: '#4a3e3d',
      skyHorizon: '#c44d27',
      skyGround: '#1f1917',
      sunElevation: 40,
      sunAzimuth: 220,
      sunKelvin: 4500,
      sunIntensity: 2.0,
      ambientIntensity: 0.8,
      ambientSky: '#5e4d4a',
      ambientGround: '#211a18',
      fogColor: '#4a3a35',
      fogDensity: 0.02,
      exposure: 0.9,
      bloom: 0.4,
      saturation: 0.65,
      contrast: 1.15,
      vignette: 0.3,
      waterColor: '#3d261d',
      waterOpacity: 0.95,
      cloudCover: 0.95
    }
  },
  {
    id: 'neon-dusk',
    name: 'Neon Dusk',
    tags: ['neon', 'synthwave', 'teal'],
    doc: 'A futuristic synthwave aesthetic with vibrant magenta/cyan gradients and teal waters.',
    params: {
      skyZenith: '#bf00ff',
      skyHorizon: '#00ffff',
      skyGround: '#120024',
      sunElevation: -1,
      sunAzimuth: 280,
      sunKelvin: 8000,
      sunIntensity: 0.5,
      ambientIntensity: 1.5,
      ambientSky: '#aa00ee',
      ambientGround: '#100020',
      fogColor: '#22003c',
      fogDensity: 0.005,
      exposure: 1.1,
      bloom: 1.0,
      saturation: 1.3,
      contrast: 1.2,
      vignette: 0.2,
      waterColor: '#00a29a',
      waterOpacity: 0.7,
      cloudCover: 0.3
    }
  }
];
