// AUTO-GENERATED by scripts/key-avatar-parts.ts — do not edit by hand.
export interface KeyedPartFile {
  file: string; raw: string; sourceFormat: 'jpeg' | 'png'; width: number; height: number;
  qa: { verdict: 'pass' | 'warn' | 'fail'; key: number[]; keyDeviation: number; coverage: number; residualMagenta: number; borderTouch: number; notes: string[] };
}
export const KEYED_PARTS: Record<string, KeyedPartFile> = {
  'eyewear-clockwork-monocle': { file: '/avatar-parts/keyed/eyewear-clockwork-monocle.png', raw: '/avatar-parts/raw/eyewear-clockwork-monocle.png', sourceFormat: 'png', width: 461, height: 512, qa: {"verdict":"pass","key":[247,3,229],"keyDeviation":27,"coverage":0.412,"residualMagenta":0,"borderTouch":0,"notes":[]} },
  'eyewear-welding-goggles': { file: '/avatar-parts/keyed/eyewear-welding-goggles.png', raw: '/avatar-parts/raw/eyewear-welding-goggles.png', sourceFormat: 'png', width: 512, height: 174, qa: {"verdict":"pass","key":[248,3,245],"keyDeviation":13,"coverage":0.639,"residualMagenta":0,"borderTouch":0,"notes":[]} },
  'headgear-aviator-helmet': { file: '/avatar-parts/keyed/headgear-aviator-helmet.png', raw: '/avatar-parts/raw/headgear-aviator-helmet.png', sourceFormat: 'png', width: 429, height: 512, qa: {"verdict":"pass","key":[249,2,248],"keyDeviation":9,"coverage":0.531,"residualMagenta":0,"borderTouch":0,"notes":[]} },
  'headgear-gear-tophat': { file: '/avatar-parts/keyed/headgear-gear-tophat.png', raw: '/avatar-parts/raw/headgear-gear-tophat.png', sourceFormat: 'png', width: 512, height: 448, qa: {"verdict":"pass","key":[247,2,247],"keyDeviation":11,"coverage":0.659,"residualMagenta":0,"borderTouch":0,"notes":[]} },
  'mouth-gold-tusk-grin': { file: '/avatar-parts/keyed/mouth-gold-tusk-grin.png', raw: '/avatar-parts/raw/mouth-gold-tusk-grin.png', sourceFormat: 'png', width: 512, height: 182, qa: {"verdict":"pass","key":[251,3,249],"keyDeviation":8,"coverage":0.707,"residualMagenta":0,"borderTouch":0,"notes":[]} },
  'neck-brass-gorget': { file: '/avatar-parts/keyed/neck-brass-gorget.png', raw: '/avatar-parts/raw/neck-brass-gorget.png', sourceFormat: 'png', width: 512, height: 307, qa: {"verdict":"pass","key":[250,2,249],"keyDeviation":8,"coverage":0.462,"residualMagenta":0,"borderTouch":0,"notes":[]} },
};
